import { nextTick } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { downloadFileAsset } from '@/api/filesApi.js'
import postApi from '@/api/postApi.js'
import loadpost from '@/components/workspace/loadpost.js'
import { useAuthStore } from '@/stores/useAuthStore.js'
import {
  PAGE_FOCUSED_WORKSPACE_PANEL_IDS,
  WORKSPACE_COVER_COLOR_OPTIONS,
  WORKSPACE_PROPERTY_PRIORITY_OPTIONS,
  WORKSPACE_PROPERTY_STATUS_OPTIONS,
  WORKSPACE_QUICK_BLOCK_OPTIONS,
  workspaceTemplates,
} from '@/constants/workspaceOptions.js'
import {
  blockTypeLabel,
  commentAnchorLabel,
  formatDateTime,
  normalizeWorkspacePageIcon,
  normalizeWorkspaceShareStatus,
  roleLabel,
  userInitial,
  workspaceAssetBadge as getWorkspaceAssetBadge,
  workspaceDocumentActionMessages,
  workspaceDocumentId,
  workspaceDocumentSectionMessages,
  workspaceRevisionReasonLabel,
  workspaceTaskTodayKey,
} from './services/index.js'
import { useWorkspaceCollaborationExperienceSetup } from './composables/useWorkspaceCollaborationExperienceSetup.js'
import { useWorkspaceCoreAccessSetup } from './composables/useWorkspaceCoreAccessSetup.js'
import { useWorkspaceDocumentExperienceSetup } from './composables/useWorkspaceDocumentExperienceSetup.js'
import { useWorkspaceDocumentOperationsExperienceSetup } from './composables/useWorkspaceDocumentOperationsExperienceSetup.js'
import { useWorkspaceEditorExperienceSetup } from './composables/useWorkspaceEditorExperienceSetup.js'
import { useWorkspaceIndexPlanningSetup } from './composables/useWorkspaceIndexPlanningSetup.js'
import { useWorkspaceMembers } from './composables/useWorkspaceMembers.js'
import { useWorkspaceNotice } from './composables/useWorkspaceNotice.js'
import { useWorkspacePeopleExperienceSetup } from './composables/useWorkspacePeopleExperienceSetup.js'
import { useWorkspaceRuntimeExperienceSetup } from './composables/useWorkspaceRuntimeExperienceSetup.js'
import { useWorkspaceState } from './composables/useWorkspaceState.js'
import { useWorkspaceSurfaceExperienceSetup } from './composables/useWorkspaceSurfaceExperienceSetup.js'

const workspaceComposables = {
  useWorkspaceCollaborationExperienceSetup,
  useWorkspaceCoreAccessSetup,
  useWorkspaceDocumentExperienceSetup,
  useWorkspaceDocumentOperationsExperienceSetup,
  useWorkspaceEditorExperienceSetup,
  useWorkspaceIndexPlanningSetup,
  useWorkspaceMembers,
  useWorkspaceNotice,
  useWorkspacePeopleExperienceSetup,
  useWorkspaceRuntimeExperienceSetup,
  useWorkspaceState,
  useWorkspaceSurfaceExperienceSetup,
}

export const useWorkspacePageSetup = () => {
  const route     = useRoute()
  const router    = useRouter()
  const authStore = useAuthStore()
  const workspacePropertyNormalizationOptions = {
    coverColorOptions: WORKSPACE_COVER_COLOR_OPTIONS,
    statusOptions: WORKSPACE_PROPERTY_STATUS_OPTIONS,
    priorityOptions: WORKSPACE_PROPERTY_PRIORITY_OPTIONS,
  }
  const workspaceState = workspaceComposables.useWorkspaceState()
  const {
    editorHolder,
    editorApi,
    title,
    isEditorLoading,
    showUserList,
    titleDirty,
    saveState,
    saveError,
    lastSavedAt,
    workspaceDocumentQuery,
    workspaceDocumentsLoading,
    workspaceMarkdownExporting,
    workspaceSectionNameDraft,
    workspaceSectionEditingId,
    workspaceSectionEditDraft,
    workspaceSectionEditInput,
    showWorkspaceShareModal,
    workspaceShareStatus,
    workspaceUuid,
    workspaceTemplateApplied,
    workspaceTemplateApplying,
    workspacePropertyIcon,
    workspacePropertyCoverColor,
    workspacePropertyStatus,
    workspacePropertyPriority,
    workspacePropertyOwnerEmail,
    workspacePropertyOwnerName,
    workspacePropertyDueDate,
    workspacePropertyTagsInput,
    workspacePageLocked,
    workspaceParentPageId,
    workspaceParentPageTitle,
    workspaceId,
    workspaceAccessRole,
    workspaceAssets,
    workspaceAssetLoading,
    workspaceAssetUploading,
    workspaceAssetError,
    deletingAssetIds,
    imageInput,
    fileInput,
    workspaceCommentInput,
    activeWorkspaceAssetId,
    savingWorkspaceAssetIds,
    workspaceComments,
    workspaceCommentLoading,
    workspaceCommentSaving,
    workspaceCommentError,
    newWorkspaceComment,
    workspaceCommentFilter,
    showWorkspaceMentionMenu,
    workspaceCommentEditingId,
    workspaceCommentEditDraft,
    newWorkspaceTask,
    newWorkspaceTaskAssignee,
    newWorkspaceTaskDueDate,
    workspaceTaskFilter,
    workspaceTaskAdding,
    workspaceInboxFilter,
    workspaceCalendarFilter,
    workspaceTimelineFilter,
    workspaceSubpageInput,
    workspaceSubpageTitle,
    workspaceSubpageCreating,
    workspaceSubpageError,
    workspaceQuickBlockText,
    workspaceInlineQuickBlockText,
    workspaceQuickBlockAdding,
    workspacePageIndexRows,
    workspacePageIndexLoading,
    workspacePageIndexError,
    workspacePageIndexFilter,
    workspacePageIndexQuery,
    workspacePageIndexTagFilter,
    workspacePageIndexOwnerFilter,
    workspacePageIndexSort,
    workspacePageIndexViewName,
    workspacePageIndexSelectedIds,
    workspacePageIndexBulkStatus,
    workspacePageIndexBulkPriority,
    workspacePageIndexBulkOwnerEmail,
    workspacePageIndexBulkDueDate,
    workspacePageIndexBulkClearDueDate,
    workspacePageIndexBulkUpdating,
    workspacePageIndexRefreshedAt,
    workspacePageIndexUpdatingIds,
    workspaceBoardDraggingId,
    workspaceBoardDragOverStatus,
    workspaceMembers,
    workspaceMemberLoading,
    workspaceMemberError,
    workspaceMemberActionLoading,
    workspaceMemberRefreshedAt,
    resolvingCommentIds,
    deletingCommentIds,
    updatingCommentIds,
    workspaceRevisions,
    workspaceRevisionLoading,
    workspaceRevisionError,
    activeWorkspaceRevision,
    workspaceRevisionDiff,
    workspaceRevisionPreviewLoading,
    workspaceRevisionRestoring,
    togglingWorkspaceTaskIds,
    togglingWorkspaceInboxTaskIds,
    openRoleDropdownId,
    activeWorkspacePanelTab,
    isWorkspacePanelCollapsed,
  } = workspaceState
  
  const coreAccessSetup = workspaceComposables.useWorkspaceCoreAccessSetup({
    platform: {
      route,
      currentUser: () => authStore.user || {},
    },
    state: {
      editorApi, title, titleDirty, saveState, workspaceId, workspaceAccessRole,
      workspacePageLocked, workspaceTemplateApplied, workspaceShareStatus,
      workspacePropertyIcon, workspacePropertyCoverColor, workspacePropertyStatus,
      workspacePropertyPriority, workspacePropertyOwnerEmail, workspacePropertyOwnerName,
      workspacePropertyDueDate, workspacePropertyTagsInput,
      workspaceParentPageId, workspaceParentPageTitle,
    },
    propertyOptions: workspacePropertyNormalizationOptions,
    documents: {
      currentWorkspaceParentPage: () => currentWorkspaceParentPage.value,
      openWorkspaceDocument: (document) => openWorkspaceDocument(document),
      workspacePageBreadcrumbTrail: () => workspacePageBreadcrumbTrail.value,
      currentWorkspaceChildPages: () => currentWorkspaceChildPages.value,
      linkedWorkspaceDocuments: () => linkedWorkspaceDocuments.value,
      workspaceBacklinks: () => workspaceBacklinks.value,
    },
  })
  const {
    normalizeWorkspaceProperties,
    normalizeWorkspaceAsset,
    normalizeWorkspaceComment,
    normalizeWorkspaceRevision,
    serializeWorkspaceSnapshotWithProperties,
    serializeWorkspaceSnapshotWithParent,
    extractWorkspacePropertiesFromContents,
    extractWorkspaceParentFromContents,
    suppressWorkspacePropertyWatch,
    applyWorkspaceProperties,
    applyWorkspaceParentPage,
    openWorkspaceParentPage,
    activeUsers,
    selectedBlockAnchor,
    documentOutline,
    documentTasks,
    documentSearchText,
    documentWorkspaceLinks,
    documentStats,
    connectionStatus,
    currentUserState,
    isValid,
    hasUnsavedChanges,
    currentUserEmail,
    currentWorkspaceKey,
    activeWorkspaceUserIds,
    workspaceRelationCount,
    confirmDiscardIfNeeded,
    allowNextRouteLeave,
    allowNextWindowUnload,
    resetLeaveGuardBypass,
    handleBeforeUnload,
    handleRouteLeave,
    handleRouteUpdate,
    currentUserIdx,
    isWorkspacePageLocked,
    canManageAssets,
    canManageWorkspaceShare,
    canEditWorkspace,
    canModifyWorkspacePage,
    shouldWorkspaceEditorReadOnly,
    workspaceLockStatusLabel,
    canShowWorkspaceTemplates,
    workspaceShareStatusLabel,
    canCommentOnWorkspace,
  } = coreAccessSetup
  const indexPlanningSetup = workspaceComposables.useWorkspaceIndexPlanningSetup({
    platform: { api: postApi },
    state: {
      workspacePageIndexRows, workspacePageIndexFilter, workspacePageIndexQuery,
      workspacePageIndexTagFilter, workspacePageIndexOwnerFilter, workspacePageIndexSort,
      workspacePageIndexSelectedIds, workspacePageIndexBulkUpdating,
      workspacePageIndexBulkStatus, workspacePageIndexBulkPriority,
      workspacePageIndexBulkOwnerEmail, workspacePageIndexBulkDueDate,
      workspacePageIndexBulkClearDueDate, currentWorkspaceKey, editorApi,
      title, titleDirty, activeWorkspacePanelTab, workspacePageIndexUpdatingIds,
      workspacePageIndexError, workspaceBoardDraggingId, workspaceBoardDragOverStatus,
      workspaceInboxFilter, workspaceCalendarFilter, workspaceTimelineFilter,
      workspacePageIndexViewName,
    },
    options: {
      priorityOptions: WORKSPACE_PROPERTY_PRIORITY_OPTIONS,
      statusOptions: WORKSPACE_PROPERTY_STATUS_OPTIONS,
    },
    documents: {
      workspaceDocuments: () => workspaceDocuments.value,
      workspacePropertyOwnerCandidates: () => workspacePropertyOwnerCandidates.value,
      documentId: workspaceDocumentId,
      workspacePageIndexRowById: () => workspacePageIndexRowById.value,
      workspaceDocumentById: () => workspaceDocumentById.value,
      createWorkspaceChildPage: (options) => createWorkspaceChildPage(options),
    },
    metadata: {
      applyWorkspaceParentPage: (parent) => applyWorkspaceParentPage(parent),
      serializeWorkspaceSnapshotWithParent: (contents, parent) => serializeWorkspaceSnapshotWithParent(contents, parent),
      extractWorkspacePropertiesFromContents: (contents) => extractWorkspacePropertiesFromContents(contents),
      normalizeWorkspaceProperties,
      applyWorkspaceProperties: (properties) => applyWorkspaceProperties(properties),
      serializeWorkspaceSnapshotWithProperties: (contents, properties) => serializeWorkspaceSnapshotWithProperties(contents, properties),
    },
    persistence: {
      persistWorkspace: (options) => persistWorkspace(options),
    },
    refreshers: {
      refreshWorkspaceDocuments: () => refreshWorkspaceDocuments(),
      refreshWorkspacePageIndex: () => refreshWorkspacePageIndex(),
    },
    user: { currentUserEmail },
  })
  const {
    workspaceFullTextResults,
    collapsedWorkspacePageTreeIds,
    pruneWorkspaceTreeEditingState,
    workspaceIndexedTasks,
    openWorkspaceIndexedTasks,
    myWorkspaceIndexedTasks,
    overdueWorkspaceCalendarItems,
    workspaceFavoriteStorageKey,
    workspaceRecentStorageKey,
    workspaceSectionsStorageKey,
    workspacePageIndexViewsStorageKey,
    favoriteWorkspaceDocumentIds,
    recentWorkspaceDocumentIds,
    workspaceDocumentSections,
    workspacePreferencesRemoteReady,
    workspacePreferencesDirtyBeforeRemoteLoad,
    loadFavoriteWorkspaceDocuments,
    persistFavoriteWorkspaceDocuments,
    loadRecentWorkspaceDocuments,
    persistRecentWorkspaceDocuments,
    pruneRecentWorkspaceDocuments,
    trackRecentWorkspaceDocument,
    loadWorkspaceDocumentSections,
    persistWorkspaceDocumentSections,
    loadWorkspacePageIndexViews,
    loadWorkspacePreferencesFromLocal,
    loadWorkspacePreferences,
    clearWorkspacePreferencesSaveTimer,
  } = indexPlanningSetup
  const editorExperienceSetup = workspaceComposables.useWorkspaceEditorExperienceSetup({
    platform: { api: postApi },
    workspaceState,
    derived: { hasUnsavedChanges, documentTasks, selectedBlockAnchor, isValid },
    options: { quickBlockOptions: WORKSPACE_QUICK_BLOCK_OPTIONS },
    access: {
      canEditWorkspace, canModifyWorkspacePage, canManageAssets,
      canManageWorkspaceShare, canCommentOnWorkspace,
    },
    user: { currentUserEmail, currentUserIdx },
    persistence: {
      persistWorkspace: (options) => persistWorkspace(options),
      ensureWorkspacePersisted: (options) => ensureWorkspacePersisted(options),
    },
    assets: {
      downloadWorkspaceAssetFile: (asset, fileName) => downloadFileAsset(asset, fileName),
      normalizeWorkspaceAsset: (asset) => normalizeWorkspaceAsset(asset),
      mergeWorkspaceAssets: (assets) => mergeWorkspaceAssets(assets),
      removeWorkspaceAssets: (assetIds) => removeWorkspaceAssets(assetIds),
    },
    comments: { normalizeWorkspaceComment: (comment) => normalizeWorkspaceComment(comment) },
    revisions: { blockTypeLabel },
    ui: { showWorkspaceNotice: (...args) => showWorkspaceNotice(...args) },
  })
  const {
    scheduleAutoSave,
    clearAutoSaveTimer,
    canInsertWorkspaceQuickBlock,
    canStartWorkspaceSubpage,
    canCreateWorkspaceSubpage,
    insertWorkspaceQuickBlock,
    toggleWorkspacePageLock,
    handleSave,
    applyWorkspaceTemplate,
    openDocumentTasks,
    completedDocumentTasks,
    overdueDocumentTasks,
    documentTaskProgress,
    documentTaskSummaryLabel,
    workspaceImages,
    workspaceFiles,
    handleEditorImageUpload,
    unresolvedWorkspaceComments,
    resolvedWorkspaceComments,
    isWorkspaceCommentMentioningCurrentUser,
    mentionedWorkspaceComments,
    workspaceBlockCommentSummaries,
    workspaceRevisionCount,
    buildWorkspaceRevisionDiff,
    upsertWorkspaceComment,
  } = editorExperienceSetup
  const peopleExperienceSetup = workspaceComposables.useWorkspacePeopleExperienceSetup({
    platform: { api: postApi },
    workspaceState,
    options: {
      quickBlockOptions: WORKSPACE_QUICK_BLOCK_OPTIONS,
      statusOptions: () => WORKSPACE_PROPERTY_STATUS_OPTIONS,
      priorityOptions: () => WORKSPACE_PROPERTY_PRIORITY_OPTIONS,
      coverColorOptions: () => WORKSPACE_COVER_COLOR_OPTIONS,
    },
    presence: { activeWorkspaceUserIds, activeUsers },
    user: { currentUser: currentUserState, currentUserEmail, currentUserIdx },
    planning: {
      currentWorkspaceKey, workspaceIndexedTasks, openWorkspaceIndexedTasks,
      myWorkspaceIndexedTasks, overdueWorkspaceCalendarItems,
      workspaceFullTextResults, workspaceRelationCount: () => workspaceRelationCount.value,
    },
    document: {
      documentStats, documentOutline, documentTaskSummaryLabel,
      openDocumentTasks, documentTaskProgress,
    },
    assets: { workspaceImages, workspaceFiles },
    comments: {
      unresolvedWorkspaceComments, resolvedWorkspaceComments,
      mentionedWorkspaceComments,
    },
    revisions: { workspaceRevisionCount },
    access: { canModifyWorkspacePage },
    persistence: { persistWorkspace: (options) => persistWorkspace(options) },
    refreshers: {
      refreshWorkspaceDocuments: () => refreshWorkspaceDocuments(),
      refreshWorkspacePageIndex: () => refreshWorkspacePageIndex(),
    },
    focus: { focusWorkspaceTaskItem: (task) => focusWorkspaceTaskItem(task) },
    ui: { showWorkspaceNotice: (...args) => showWorkspaceNotice(...args) },
    formatters: { initialFor: userInitial, formatDateTimeFor: formatDateTime },
  })
  const {
    workspaceMemberRows,
    workspacePanelTabs,
    workspacePropertyTags,
    workspacePropertyOwnerCandidates,
    selectedWorkspacePropertyOwner,
    workspacePropertyStatusOption,
    workspacePropertyPriorityOption,
  } = peopleExperienceSetup
  const documentExperienceSetup = workspaceComposables.useWorkspaceDocumentExperienceSetup({
    platform: { api: postApi },
    workspaceState,
    documentState: {
      workspaceDocumentSections, favoriteWorkspaceDocumentIds, recentWorkspaceDocumentIds,
    },
    derived: {
      currentWorkspaceKey, hasUnsavedChanges, isValid, workspacePanelTabs, connectionStatus,
    },
    documents: {
      personalItems: loadpost.personalItems,
      sharedItems: loadpost.sharedItems,
      loadDocuments: () => loadpost.side_list(),
    },
    options: {
      propertyOptions: workspacePropertyNormalizationOptions,
      statusOptions: () => WORKSPACE_PROPERTY_STATUS_OPTIONS,
      priorityOptions: () => WORKSPACE_PROPERTY_PRIORITY_OPTIONS,
      quickBlockOptions: WORKSPACE_QUICK_BLOCK_OPTIONS,
      workspaceTemplates,
      pageFocusedPanelIds: PAGE_FOCUSED_WORKSPACE_PANEL_IDS,
    },
    access: {
      canEditWorkspace, isWorkspacePageLocked,
      canFavoriteCurrentWorkspaceDocument: () => canFavoriteCurrentWorkspaceDocument.value,
      isCurrentWorkspaceDocumentFavorite: () => isCurrentWorkspaceDocumentFavorite.value,
      canManageWorkspaceShare,
      canExportWorkspaceMarkdown: () => canExportWorkspaceMarkdown.value,
      canStartWorkspaceSubpage, canShowWorkspaceTemplates, canInsertWorkspaceQuickBlock,
      canModifyWorkspacePage, workspaceLockStatusLabel, canCommentOnWorkspace, canManageAssets,
    },
    people: {
      selectedWorkspacePropertyOwner, workspacePropertyTags, currentUserEmail,
      mentionedWorkspaceComments, workspaceMemberRows,
      workspacePropertyStatusOption, workspacePropertyPriorityOption,
    },
    editor: {
      documentSearchText, documentWorkspaceLinks, documentStats, documentTasks,
      documentTaskProgress, completedDocumentTasks, overdueDocumentTasks,
    },
    comments: { unresolvedWorkspaceComments, resolvedWorkspaceComments, mentionedWorkspaceComments },
    assets: { workspaceImages, workspaceFiles },
    sharing: { workspaceShareStatusLabel },
    preferences: {
      loadWorkspaceDocumentSections: () => loadWorkspaceDocumentSections(),
      pruneRecentWorkspaceDocuments: () => pruneRecentWorkspaceDocuments(),
      persistRecentWorkspaceDocuments: () => persistRecentWorkspaceDocuments(),
    },
    formatters: {
      workspaceTaskTodayKeyFor: workspaceTaskTodayKey,
      formatDateTimeFor: formatDateTime,
      roleLabelFor: roleLabel,
    },
  })
  const {
    workspaceDocuments,
    workspaceDocumentById,
    workspacePageIndexRowById,
    workspacePageBreadcrumbTrail,
    currentWorkspaceParentPage,
    linkedWorkspaceDocuments,
    currentWorkspaceChildPages,
    currentWorkspaceProperties,
    workspaceCommandBaseItems,
    workspaceBacklinks,
    refreshWorkspaceBacklinks,
    refreshWorkspacePageIndex,
    refreshWorkspaceDocuments,
  } = documentExperienceSetup
  const {
    workspaceNotice,
    workspaceConfirm,
    clearWorkspaceNoticeTimer,
    closeWorkspaceNotice,
    showWorkspaceNotice,
    runWorkspaceNoticeAction,
    closeWorkspaceConfirm,
    requestWorkspaceConfirm,
    confirmWorkspaceAction,
  } = workspaceComposables.useWorkspaceNotice()
  const membersSetup = workspaceComposables.useWorkspaceMembers({
    workspaceId,
    workspaceMembers,
    workspaceMemberLoading,
    workspaceMemberError,
    workspaceMemberActionLoading,
    workspaceMemberRefreshedAt,
    openRoleDropdownId,
    currentUserIdx,
    canManageWorkspaceShare,
    fetchWorkspaceMembers: (targetWorkspaceId) => postApi.loadRole(targetWorkspaceId),
    changeWorkspaceUserRole: (targetWorkspaceId, targetUserIdx, role) => postApi.changeUserRole(targetWorkspaceId, targetUserIdx, role),
    kickWorkspaceUser: (targetWorkspaceId, targetUserIdx) => postApi.kickUser(targetWorkspaceId, targetUserIdx),
    showWorkspaceNotice,
    requestWorkspaceConfirm,
  })
  const {
    refreshWorkspaceMembers,
    closeRoleDropdown,
  } = membersSetup
  const documentOperationsExperienceSetup = workspaceComposables.useWorkspaceDocumentOperationsExperienceSetup({
    platform: { route, router, api: postApi },
    workspaceState,
    documentState: { workspaceDocumentSections, favoriteWorkspaceDocumentIds },
    derived: { currentWorkspaceKey, hasUnsavedChanges },
    people: { workspacePropertyStatusOption, workspacePropertyPriorityOption, workspacePropertyTags },
    access: { canModifyWorkspacePage, canStartWorkspaceSubpage, canCreateWorkspaceSubpage },
    propertyOptions: workspacePropertyNormalizationOptions,
    preferences: {
      trackRecentWorkspaceDocument,
      persistFavoriteWorkspaceDocuments,
      persistWorkspaceDocumentSections,
    },
    workspace: {
      workspaceDocumentById, currentWorkspaceProperties,
      ensureWorkspacePersisted: (options) => ensureWorkspacePersisted(options),
      persistWorkspace: (options) => persistWorkspace(options),
    },
    guards: { confirmDiscardIfNeeded, allowNextRouteLeave },
    editor: { setupEditor: () => setupEditor() },
    refreshers: {
      refreshWorkspaceDocuments: () => refreshWorkspaceDocuments(),
      refreshWorkspacePageIndex: () => refreshWorkspacePageIndex(),
    },
    metadata: {
      applyWorkspaceProperties: (properties) => applyWorkspaceProperties(properties),
      applyWorkspaceParentPage: (parent) => applyWorkspaceParentPage(parent),
      extractWorkspacePropertiesFromContents: (contents) => extractWorkspacePropertiesFromContents(contents),
      extractWorkspaceParentFromContents: (contents) => extractWorkspaceParentFromContents(contents),
    },
    normalizers: {
      normalizeWorkspaceRevision: (revision) => normalizeWorkspaceRevision(revision),
      buildWorkspaceRevisionDiff: (revision) => buildWorkspaceRevisionDiff(revision),
      normalizeWorkspaceShareStatus: (status, type) => normalizeWorkspaceShareStatus(status, type),
    },
    ui: {
      requestWorkspaceConfirm: (options) => requestWorkspaceConfirm(options),
      showWorkspaceNotice: (...args) => showWorkspaceNotice(...args),
    },
    messages: {
      sectionMessages: workspaceDocumentSectionMessages,
      actionMessages: workspaceDocumentActionMessages,
    },
    documentIdFor: workspaceDocumentId,
  })
  const {
    clearWorkspaceDocumentLinkCopyTimer,
    openWorkspaceDocument,
    createWorkspaceDocument,
    canExportWorkspaceMarkdown,
    exportWorkspaceMarkdown,
    toggleCurrentWorkspaceDocumentFavorite,
    canFavoriteCurrentWorkspaceDocument,
    isCurrentWorkspaceDocumentFavorite,
    focusWorkspaceSubpageComposer,
    createWorkspaceChildPage,
    refreshWorkspaceRevisions,
  } = documentOperationsExperienceSetup
  const collaborationExperienceSetup = workspaceComposables.useWorkspaceCollaborationExperienceSetup({
    platform: {
      api: postApi,
      route,
      router,
      authStore,
      waitForDomUpdate: () => nextTick(),
    },
    workspaceState,
    derived: {
      hasUnsavedChanges,
      workspaceBlockCommentSummaries,
      currentWorkspaceKey,
      workspaceCommandBaseItems,
      workspaceNotice,
      workspaceConfirm,
    },
    access: { currentUserIdx, canManageWorkspaceShare, canCommentOnWorkspace },
    normalizers: {
      normalizeWorkspaceAsset,
      normalizeWorkspaceComment,
      isWorkspaceCommentMentioningCurrentUser,
      commentAnchorLabel,
      upsertWorkspaceComment,
      normalizeWorkspaceShareStatus,
    },
    refreshers: {
      refreshWorkspaceDocuments,
      refreshWorkspaceRevisions,
      refreshWorkspaceMembers,
    },
    persistence: { allowNextRouteLeave },
    documents: { openWorkspaceDocument, createWorkspaceDocument, openWorkspaceParentPage },
    commands: {
      applyWorkspaceTemplate,
      insertWorkspaceQuickBlock,
      handleSave,
      toggleWorkspacePageLock,
      toggleCurrentWorkspaceDocumentFavorite,
      exportWorkspaceMarkdown,
      focusWorkspaceSubpageComposer,
    },
    ui: {
      showWorkspaceNotice,
      runWorkspaceNoticeAction,
      closeWorkspaceNotice,
      closeWorkspaceConfirm,
      confirmWorkspaceAction,
    },
  })
  const {
    refreshWorkspaceAssets,
    refreshWorkspaceComments,
    mergeWorkspaceAssets,
    removeWorkspaceAssets,
    connectWorkspaceAssetRealtime,
    disconnectWorkspaceAssetRealtime,
    persistWorkspace,
    ensureWorkspacePersisted,
    applyWorkspaceBlockCommentSummaries,
    handleEditorBlockCommentBadgeClick,
    focusWorkspaceTaskItem,
    handleWorkspaceGlobalKeydown,
    workspaceOverlaysModel,
    workspaceOverlaysActions,
  } = collaborationExperienceSetup
  workspaceComposables.useWorkspaceRuntimeExperienceSetup({
    workspaceState,
    platform: { route, router, api: postApi, authStore },
    runtime: {
      handleRouteLeave, handleRouteUpdate, handleBeforeUnload,
      allowNextRouteLeave, allowNextWindowUnload, resetLeaveGuardBypass,
      handleWorkspaceGlobalKeydown, closeRoleDropdown, showWorkspaceNotice,
      closeWorkspaceConfirm, clearWorkspaceNoticeTimer,
      shouldWorkspaceEditorReadOnly, currentWorkspaceProperties, workspaceDocumentById,
      normalizeWorkspaceShareStatus, trackRecentWorkspaceDocument,
      applyWorkspaceProperties, applyWorkspaceParentPage,
      extractWorkspacePropertiesFromContents, extractWorkspaceParentFromContents,
      refreshWorkspaceAssets, refreshWorkspaceComments, refreshWorkspaceRevisions,
      refreshWorkspaceMembers, refreshWorkspaceDocuments, refreshWorkspaceBacklinks,
      handleEditorImageUpload, scheduleAutoSave, handleEditorBlockCommentBadgeClick,
      applyWorkspaceBlockCommentSummaries, selectedBlockAnchor, workspaceBlockCommentSummaries,
      workspaceFavoriteStorageKey, workspaceRecentStorageKey, workspaceSectionsStorageKey,
      workspacePageIndexViewsStorageKey, currentUserEmail, collapsedWorkspacePageTreeIds,
      suppressWorkspacePropertyWatch, workspacePreferencesRemoteReady,
      workspacePreferencesDirtyBeforeRemoteLoad, loadWorkspacePreferencesFromLocal,
      loadWorkspacePreferences, loadFavoriteWorkspaceDocuments, loadRecentWorkspaceDocuments,
      loadWorkspaceDocumentSections, loadWorkspacePageIndexViews, clearWorkspacePreferencesSaveTimer,
      clearAutoSaveTimer, pruneWorkspaceTreeEditingState, connectWorkspaceAssetRealtime,
      disconnectWorkspaceAssetRealtime, clearWorkspaceDocumentLinkCopyTimer,
    },
  })
  const {
    workspaceFloatingPanelStackModel,
    workspaceFloatingPanelStackActions,
    workspaceMainLayoutModel,
    workspaceMainLayoutActions,
  } = workspaceComposables.useWorkspaceSurfaceExperienceSetup({
    state: workspaceState,
    options: {
      workspacePropertyStatusOptions: WORKSPACE_PROPERTY_STATUS_OPTIONS,
      workspacePropertyPriorityOptions: WORKSPACE_PROPERTY_PRIORITY_OPTIONS,
      workspaceQuickBlockOptions: WORKSPACE_QUICK_BLOCK_OPTIONS,
      workspaceTemplates,
    },
    groups: {
      coreAccess: coreAccessSetup,
      indexPlanning: indexPlanningSetup,
      editorExperience: editorExperienceSetup,
      peopleExperience: peopleExperienceSetup,
      documentExperience: documentExperienceSetup,
      members: membersSetup,
      documentOperations: documentOperationsExperienceSetup,
      collaboration: collaborationExperienceSetup,
    },
    services: {
      roleLabel,
      userInitial,
      workspaceTaskTodayKey,
      workspaceRevisionReasonLabel,
      commentAnchorLabel,
      getWorkspaceAssetBadge,
      normalizeWorkspacePageIcon,
    },
    refs: {
      registerSubpageInput: (value) => { workspaceSubpageInput.value = value },
      registerCommentInput: (value) => { workspaceCommentInput.value = value },
    },
  })

  return {
    isWorkspacePanelCollapsed,
    workspaceOverlaysModel,
    workspaceOverlaysActions,
    workspaceMainLayoutModel,
    workspaceMainLayoutActions,
    workspaceFloatingPanelStackModel,
    workspaceFloatingPanelStackActions,
  }
}
