import { useWorkspaceDocumentShellSetup } from './useWorkspaceDocumentShellSetup.js'

export const createWorkspaceDocumentExperienceGroups = ({
  platform = {},
  workspaceState = {},
  documentState = {},
  derived = {},
  documents = {},
  options = {},
  access = {},
  people = {},
  editor = {},
  comments = {},
  assets = {},
  sharing = {},
  preferences = {},
  formatters = {},
} = {}) => ({
  platform,
  state: {
    workspaceDocumentQuery: workspaceState.workspaceDocumentQuery,
    workspaceDocumentSections: documentState.workspaceDocumentSections,
    workspacePageIndexRows: workspaceState.workspacePageIndexRows,
    currentWorkspaceKey: derived.currentWorkspaceKey,
    workspaceParentPageId: workspaceState.workspaceParentPageId,
    workspaceParentPageTitle: workspaceState.workspaceParentPageTitle,
    favoriteWorkspaceDocumentIds: documentState.favoriteWorkspaceDocumentIds,
    recentWorkspaceDocumentIds: documentState.recentWorkspaceDocumentIds,
    workspacePropertyIcon: workspaceState.workspacePropertyIcon,
    workspacePropertyCoverColor: workspaceState.workspacePropertyCoverColor,
    workspacePropertyStatus: workspaceState.workspacePropertyStatus,
    workspacePropertyPriority: workspaceState.workspacePropertyPriority,
    workspacePropertyOwnerEmail: workspaceState.workspacePropertyOwnerEmail,
    workspacePropertyOwnerName: workspaceState.workspacePropertyOwnerName,
    workspacePropertyDueDate: workspaceState.workspacePropertyDueDate,
    workspacePageLocked: workspaceState.workspacePageLocked,
    hasUnsavedChanges: derived.hasUnsavedChanges,
    isValid: derived.isValid,
    activeWorkspacePanelTab: workspaceState.activeWorkspacePanelTab,
    workspacePanelTabs: derived.workspacePanelTabs,
    workspaceId: workspaceState.workspaceId,
    title: workspaceState.title,
    saveState: workspaceState.saveState,
    saveError: workspaceState.saveError,
    lastSavedAt: workspaceState.lastSavedAt,
    connectionStatus: derived.connectionStatus,
    workspaceAccessRole: workspaceState.workspaceAccessRole,
    workspaceShareStatus: workspaceState.workspaceShareStatus,
    workspacePageIndexLoading: workspaceState.workspacePageIndexLoading,
    workspacePageIndexError: workspaceState.workspacePageIndexError,
    workspacePageIndexRefreshedAt: workspaceState.workspacePageIndexRefreshedAt,
    workspaceDocumentsLoading: workspaceState.workspaceDocumentsLoading,
    workspaceMemberLoading: workspaceState.workspaceMemberLoading,
  },
  documents,
  options,
  access,
  people,
  editor,
  comments,
  assets: {
    workspaceAssets: workspaceState.workspaceAssets,
    workspaceImages: assets.workspaceImages,
    workspaceFiles: assets.workspaceFiles,
  },
  sharing,
  preferences,
  formatters,
})

export const useWorkspaceDocumentExperienceSetup = (groups = {}) =>
  useWorkspaceDocumentShellSetup(createWorkspaceDocumentExperienceGroups(groups))
