import { useWorkspaceHomePanels } from './useWorkspaceHomePanels.js'
import { useWorkspacePeopleOptions } from './useWorkspacePeopleOptions.js'
import { useWorkspaceTaskMutations } from './useWorkspaceTaskMutations.js'

export const useWorkspacePeopleTaskSetup = ({
  platform = {},
  state = {},
  options = {},
  presence = {},
  user = {},
  planning = {},
  document = {},
  assets = {},
  comments = {},
  revisions = {},
  access = {},
  persistence = {},
  refreshers = {},
  focus = {},
  ui = {},
  formatters = {},
} = {}) => {
  const homePanels = useWorkspaceHomePanels({
    workspaceMembers: state.workspaceMembers,
    currentUserIdx: user.currentUserIdx,
    activeWorkspaceUserIds: presence.activeWorkspaceUserIds,
    currentUser: user.currentUser,
    activeUsers: presence.activeUsers,
    workspacePageIndexRows: planning.workspacePageIndexRows,
    workspaceIndexedTasks: planning.workspaceIndexedTasks,
    openWorkspaceIndexedTasks: planning.openWorkspaceIndexedTasks,
    myWorkspaceIndexedTasks: planning.myWorkspaceIndexedTasks,
    currentUserEmail: user.currentUserEmail,
    initialFor: formatters.initialFor,
    documentStats: document.documentStats,
    documentOutline: document.documentOutline,
    documentTaskSummaryLabel: document.documentTaskSummaryLabel,
    openDocumentTasks: document.openDocumentTasks,
    documentTaskProgress: document.documentTaskProgress,
    unresolvedWorkspaceComments: comments.unresolvedWorkspaceComments,
    resolvedWorkspaceComments: comments.resolvedWorkspaceComments,
    mentionedWorkspaceComments: comments.mentionedWorkspaceComments,
    workspaceAssets: assets.workspaceAssets,
    workspaceImages: assets.workspaceImages,
    workspaceFiles: assets.workspaceFiles,
    overdueWorkspaceCalendarItems: planning.overdueWorkspaceCalendarItems,
    lastSavedAt: state.lastSavedAt,
    workspaceComments: comments.workspaceComments,
    workspaceMemberRefreshedAt: state.workspaceMemberRefreshedAt,
    formatDateTimeFor: formatters.formatDateTimeFor,
    workspaceFullTextResults: planning.workspaceFullTextResults,
    quickBlockOptions: options.quickBlockOptions,
    workspaceRelationCount: planning.workspaceRelationCount,
    workspaceRevisionCount: revisions.workspaceRevisionCount,
  })

  const peopleOptions = useWorkspacePeopleOptions({
    workspaceMemberRows: homePanels.workspaceMemberRows,
    activeUsers: presence.activeUsers,
    currentUser: user.currentUser,
    currentUserIdx: user.currentUserIdx,
    newWorkspaceTaskAssignee: state.newWorkspaceTaskAssignee,
    workspacePropertyTagsInput: state.workspacePropertyTagsInput,
    workspacePropertyOwnerEmail: state.workspacePropertyOwnerEmail,
    workspacePropertyOwnerName: state.workspacePropertyOwnerName,
    workspacePropertyStatus: state.workspacePropertyStatus,
    workspacePropertyPriority: state.workspacePropertyPriority,
    workspacePropertyCoverColor: state.workspacePropertyCoverColor,
    statusOptions: options.statusOptions,
    priorityOptions: options.priorityOptions,
    coverColorOptions: options.coverColorOptions,
    initialFor: formatters.initialFor,
  })

  const taskMutations = useWorkspaceTaskMutations({
    togglingWorkspaceTaskIds: state.togglingWorkspaceTaskIds,
    togglingWorkspaceInboxTaskIds: state.togglingWorkspaceInboxTaskIds,
    canModifyWorkspacePage: access.canModifyWorkspacePage,
    editorApi: state.editorApi,
    currentWorkspaceKey: state.currentWorkspaceKey,
    fetchWorkspaceDocument: (documentId) => platform.api?.getPost?.(documentId),
    saveWorkspaceDocument: (payload) => platform.api?.savePost?.(payload),
    persistWorkspace: persistence.persistWorkspace,
    refreshWorkspaceDocuments: refreshers.refreshWorkspaceDocuments,
    refreshWorkspacePageIndex: refreshers.refreshWorkspacePageIndex,
    focusWorkspaceTaskItem: focus.focusWorkspaceTaskItem,
    showWorkspaceNotice: ui.showWorkspaceNotice,
    newWorkspaceTask: state.newWorkspaceTask,
    selectedWorkspaceTaskAssignee: peopleOptions.selectedWorkspaceTaskAssignee,
    newWorkspaceTaskDueDate: state.newWorkspaceTaskDueDate,
    workspaceTaskAdding: state.workspaceTaskAdding,
  })

  return {
    ...homePanels,
    ...peopleOptions,
    ...taskMutations,
  }
}
