import { useWorkspaceCollaborationCommandSetup } from './useWorkspaceCollaborationCommandSetup.js'

export const createWorkspaceCollaborationExperienceGroups = ({
  platform = {},
  workspaceState = {},
  derived = {},
  access = {},
  normalizers = {},
  refreshers = {},
  persistence = {},
  documents = {},
  commands = {},
  ui = {},
} = {}) => ({
  platform,
  state: {
    workspaceId: workspaceState.workspaceId,
    workspaceAssets: workspaceState.workspaceAssets,
    workspaceAssetLoading: workspaceState.workspaceAssetLoading,
    workspaceAssetError: workspaceState.workspaceAssetError,
    workspaceComments: workspaceState.workspaceComments,
    workspaceCommentLoading: workspaceState.workspaceCommentLoading,
    workspaceCommentError: workspaceState.workspaceCommentError,
    isWorkspacePanelCollapsed: workspaceState.isWorkspacePanelCollapsed,
    activeWorkspacePanelTab: workspaceState.activeWorkspacePanelTab,
    workspaceCommentFilter: workspaceState.workspaceCommentFilter,
    activeWorkspaceAssetId: workspaceState.activeWorkspaceAssetId,
    editorApi: workspaceState.editorApi,
    workspaceAccessRole: workspaceState.workspaceAccessRole,
    workspaceShareStatus: workspaceState.workspaceShareStatus,
    workspaceUuid: workspaceState.workspaceUuid,
    titleDirty: workspaceState.titleDirty,
    saveState: workspaceState.saveState,
    saveError: workspaceState.saveError,
    lastSavedAt: workspaceState.lastSavedAt,
    showWorkspaceShareModal: workspaceState.showWorkspaceShareModal,
    isEditorLoading: workspaceState.isEditorLoading,
    hasUnsavedChanges: derived.hasUnsavedChanges,
    workspaceCommentInput: workspaceState.workspaceCommentInput,
    newWorkspaceComment: workspaceState.newWorkspaceComment,
    showWorkspaceMentionMenu: workspaceState.showWorkspaceMentionMenu,
    workspaceBlockCommentSummaries: derived.workspaceBlockCommentSummaries,
    currentWorkspaceKey: derived.currentWorkspaceKey,
    workspaceCommandBaseItems: derived.workspaceCommandBaseItems,
    workspaceNotice: derived.workspaceNotice,
    workspaceConfirm: derived.workspaceConfirm,
  },
  access,
  normalizers,
  refreshers,
  persistence,
  documents,
  commands,
  ui,
})

export const useWorkspaceCollaborationExperienceSetup = (groups = {}) =>
  useWorkspaceCollaborationCommandSetup(createWorkspaceCollaborationExperienceGroups(groups))
