import { useWorkspaceRuntimeLifecycle } from './useWorkspaceRuntimeLifecycle.js'

export const createWorkspaceRuntimePropertySources = (state = {}) => [
  state.workspacePropertyIcon,
  state.workspacePropertyCoverColor,
  state.workspacePropertyStatus,
  state.workspacePropertyPriority,
  state.workspacePropertyOwnerEmail,
  state.workspacePropertyDueDate,
  state.workspacePropertyTagsInput,
  state.workspacePageLocked,
]

export const useWorkspaceRuntimeLifecycleSetup = ({
  state = {},
  platform = {},
  guards = {},
  ui = {},
  workspace = {},
  metadata = {},
  refreshers = {},
  editor = {},
  preferences = {},
  lifecycle = {},
} = {}) => useWorkspaceRuntimeLifecycle({
  ...state,
  route: platform.route,
  router: platform.router,
  api: platform.api,
  authStore: platform.authStore,
  handleRouteLeave: guards.handleRouteLeave,
  handleRouteUpdate: guards.handleRouteUpdate,
  handleBeforeUnload: guards.handleBeforeUnload,
  allowNextRouteLeave: guards.allowNextRouteLeave,
  allowNextWindowUnload: guards.allowNextWindowUnload,
  resetLeaveGuardBypass: guards.resetLeaveGuardBypass,
  handleWorkspaceGlobalKeydown: ui.handleWorkspaceGlobalKeydown,
  closeRoleDropdown: ui.closeRoleDropdown,
  showWorkspaceNotice: ui.showWorkspaceNotice,
  closeWorkspaceConfirm: ui.closeWorkspaceConfirm,
  clearWorkspaceNoticeTimer: ui.clearWorkspaceNoticeTimer,
  shouldWorkspaceEditorReadOnly: workspace.shouldWorkspaceEditorReadOnly,
  currentWorkspaceProperties: workspace.currentWorkspaceProperties,
  workspaceDocumentById: workspace.workspaceDocumentById,
  normalizeWorkspaceShareStatus: workspace.normalizeWorkspaceShareStatus,
  trackRecentWorkspaceDocument: workspace.trackRecentWorkspaceDocument,
  applyWorkspaceProperties: metadata.applyWorkspaceProperties,
  applyWorkspaceParentPage: metadata.applyWorkspaceParentPage,
  extractWorkspacePropertiesFromContents: metadata.extractWorkspacePropertiesFromContents,
  extractWorkspaceParentFromContents: metadata.extractWorkspaceParentFromContents,
  refreshWorkspaceAssets: refreshers.refreshWorkspaceAssets,
  refreshWorkspaceComments: refreshers.refreshWorkspaceComments,
  refreshWorkspaceRevisions: refreshers.refreshWorkspaceRevisions,
  refreshWorkspaceMembers: refreshers.refreshWorkspaceMembers,
  refreshWorkspaceDocuments: refreshers.refreshWorkspaceDocuments,
  refreshWorkspaceBacklinks: refreshers.refreshWorkspaceBacklinks,
  handleEditorImageUpload: editor.handleEditorImageUpload,
  scheduleAutoSave: editor.scheduleAutoSave,
  handleEditorBlockCommentBadgeClick: editor.handleEditorBlockCommentBadgeClick,
  applyWorkspaceBlockCommentSummaries: editor.applyWorkspaceBlockCommentSummaries,
  selectedBlockAnchor: editor.selectedBlockAnchor,
  workspaceBlockCommentSummaries: editor.workspaceBlockCommentSummaries,
  workspaceFavoriteStorageKey: preferences.workspaceFavoriteStorageKey,
  workspaceRecentStorageKey: preferences.workspaceRecentStorageKey,
  workspaceSectionsStorageKey: preferences.workspaceSectionsStorageKey,
  workspacePageIndexViewsStorageKey: preferences.workspacePageIndexViewsStorageKey,
  currentUserEmail: preferences.currentUserEmail,
  collapsedWorkspacePageTreeIds: preferences.collapsedWorkspacePageTreeIds,
  workspacePropertySources: createWorkspaceRuntimePropertySources(state),
  suppressWorkspacePropertyWatch: preferences.suppressWorkspacePropertyWatch,
  workspacePreferencesRemoteReady: preferences.workspacePreferencesRemoteReady,
  workspacePreferencesDirtyBeforeRemoteLoad: preferences.workspacePreferencesDirtyBeforeRemoteLoad,
  loadWorkspacePreferencesFromLocal: preferences.loadWorkspacePreferencesFromLocal,
  loadWorkspacePreferences: preferences.loadWorkspacePreferences,
  loadFavoriteWorkspaceDocuments: preferences.loadFavoriteWorkspaceDocuments,
  loadRecentWorkspaceDocuments: preferences.loadRecentWorkspaceDocuments,
  loadWorkspaceDocumentSections: preferences.loadWorkspaceDocumentSections,
  loadWorkspacePageIndexViews: preferences.loadWorkspacePageIndexViews,
  clearWorkspacePreferencesSaveTimer: preferences.clearWorkspacePreferencesSaveTimer,
  clearAutoSaveTimer: lifecycle.clearAutoSaveTimer,
  pruneWorkspaceTreeEditingState: lifecycle.pruneWorkspaceTreeEditingState,
  connectWorkspaceAssetRealtime: lifecycle.connectWorkspaceAssetRealtime,
  disconnectWorkspaceAssetRealtime: lifecycle.disconnectWorkspaceAssetRealtime,
  clearWorkspaceDocumentLinkCopyTimer: lifecycle.clearWorkspaceDocumentLinkCopyTimer,
})