import { computed, unref } from 'vue'

const noop = () => {}

export const createWorkspaceFloatingPanelValueSetter = (mutableValues = {}) => (key, value) => {
  const target = mutableValues[key]
  if (target && typeof target === 'object' && 'value' in target) {
    target.value = value
  }
}

export const createWorkspaceFloatingPanelMutableValues = ({
  activeWorkspacePanelTab,
  workspaceFullTextQuery,
  workspacePageTreeQuery,
  workspaceTreeSubpageTitle,
  workspaceTreeRenameDraft,
  workspaceTreeMoveTargetId,
  workspacePageIndexFilter,
  workspacePageIndexQuery,
  workspacePageIndexSort,
  workspacePageIndexOwnerFilter,
  workspacePageIndexTagFilter,
  workspacePageIndexViewName,
  workspacePageIndexBulkStatus,
  workspacePageIndexBulkPriority,
  workspacePageIndexBulkOwnerEmail,
  workspacePageIndexBulkDueDate,
  workspacePageIndexBulkClearDueDate,
  workspaceTimelineFilter,
  workspaceCalendarFilter,
  workspaceInboxFilter,
  workspaceQuickBlockText,
  newWorkspaceTask,
  newWorkspaceTaskAssignee,
  newWorkspaceTaskDueDate,
  workspaceTaskFilter,
  workspaceSubpageTitle,
  workspaceCommentFilter,
  showWorkspaceMentionMenu,
  newWorkspaceComment,
  workspaceCommentEditDraft,
} = {}) => ({
  activeWorkspacePanelTab,
  workspaceFullTextQuery,
  workspacePageTreeQuery,
  workspaceTreeSubpageTitle,
  workspaceTreeRenameDraft,
  workspaceTreeMoveTargetId,
  workspacePageIndexFilter,
  workspacePageIndexQuery,
  workspacePageIndexSort,
  workspacePageIndexOwnerFilter,
  workspacePageIndexTagFilter,
  workspacePageIndexViewName,
  workspacePageIndexBulkStatus,
  workspacePageIndexBulkPriority,
  workspacePageIndexBulkOwnerEmail,
  workspacePageIndexBulkDueDate,
  workspacePageIndexBulkClearDueDate,
  workspaceTimelineFilter,
  workspaceCalendarFilter,
  workspaceInboxFilter,
  workspaceQuickBlockText,
  newWorkspaceTask,
  newWorkspaceTaskAssignee,
  newWorkspaceTaskDueDate,
  workspaceTaskFilter,
  workspaceSubpageTitle,
  workspaceCommentFilter,
  showWorkspaceMentionMenu,
  newWorkspaceComment,
  workspaceCommentEditDraft,
})

export const useWorkspaceFloatingPanelStackBridge = (context = {}) => {
  const {
    activeWorkspacePanelTab,
    isWorkspacePanelCollapsed,
    workspacePanelTabs,
    isWorkspacePanelVisible,
    workspacePageIndexLoading,
    workspaceHomeMetricCards,
    workspaceHomeAttentionItems,
    workspaceHomeMyQueue,
    workspaceHomeRecentPages,
    documentStats,
    workspaceSummaryCards,
    workspaceHealthItems,
    activeUsers,
    workspaceAccessRole,
    workspaceShareStatusLabel,
    workspacePermissionItems,
    canManageWorkspaceShare,
    canManageAssets,
    canCommentOnWorkspace,
    isValid,
    isSaving,
    isEditorLoading,
    workspaceShareButtonTitle,
    workspaceAssetUploading,
    workspaceId,
    workspaceMemberSummaryLabel,
    workspaceMemberError,
    workspaceMemberLoading,
    workspaceMemberRows,
    roleLabel,
    userInitial,
    isWorkspaceMemberBusy,
    workspaceWorkloadRows,
    workspaceFullTextQuery,
    workspaceFullTextResults,
    workspaceFullTextLoading,
    workspaceFullTextError,
    canSearchWorkspaceFullText,
    canModifyWorkspacePage,
    editorApi,
    workspacePageTreeQuery,
    workspaceTreeSubpageTitle,
    workspaceTreeRenameDraft,
    workspaceTreeMoveTargetId,
    workspacePageTreeVisibleRows,
    workspacePageTreeEmptyLabel,
    workspacePageTreeCollapsedIdSet,
    workspaceTreeSubpageError,
    workspaceTreeRenameError,
    workspaceTreeMoveError,
    workspaceTreeSubpageCreatingId,
    workspaceTreeSubpageComposerParentId,
    workspaceTreeRenamingId,
    workspaceTreeRenameSavingId,
    workspaceTreeMovingId,
    workspaceTreeMoveSavingId,
    isWorkspaceDocumentLinkCopied,
    workspaceTreeMoveTargetOptions,
    canApplyWorkspaceTreeMove,
    workspacePageIndexError,
    workspacePageIndexFilter,
    workspacePageIndexFilterOptions,
    workspacePageIndexQuery,
    workspacePageIndexSort,
    workspacePageIndexSortOptions,
    workspacePageIndexOwnerFilter,
    workspacePageIndexOwnerFilterOptions,
    workspacePageIndexTagFilter,
    workspacePageIndexTagOptions,
    workspacePageIndexViews,
    activeWorkspacePageIndexView,
    workspacePageIndexViewName,
    canCreateWorkspacePageIndexView,
    visibleEditableWorkspacePageIndexRows,
    selectedWorkspacePageIndexRows,
    areAllVisibleWorkspacePageIndexRowsSelected,
    canApplyWorkspacePageIndexBulkUpdate,
    workspacePageIndexBulkStatus,
    workspacePageIndexBulkPriority,
    workspacePageIndexBulkOwnerEmail,
    workspacePageIndexBulkDueDate,
    workspacePageIndexBulkClearDueDate,
    workspacePageIndexBulkUpdating,
    workspacePropertyOwnerCandidates,
    workspacePropertyStatusOptions = [],
    workspacePropertyPriorityOptions = [],
    visibleWorkspacePageIndexRows,
    workspacePageIndexOwnerOptions,
    isWorkspacePageIndexRowSelected,
    isWorkspacePageIndexRowUpdating,
    workspacePageIndexViewSummary,
    workspaceBoardRows,
    workspaceBoardColumns,
    workspaceBoardDraggingId,
    workspaceBoardDragOverStatus,
    workspaceTimelineFilter,
    workspaceTimelineFilterOptions,
    workspaceTimelineRange,
    workspaceTimelineGroups,
    workspaceTimelineEmptyLabel,
    workspaceTimelineItemStyle,
    workspaceCalendarFilter,
    workspaceCalendarFilterOptions,
    workspaceCalendarGroups,
    workspaceCalendarEmptyLabel,
    workspaceTaskTodayKey = () => '',
    openWorkspaceIndexedTasks,
    workspaceInboxFilterOptions,
    workspaceInboxFilter,
    visibleWorkspaceInboxTasks,
    workspaceInboxEmptyLabel,
    isWorkspaceInboxTaskToggling,
    workspaceActivityItems,
    workspaceQuickBlockOptions = [],
    workspaceQuickBlockText,
    workspaceQuickBlockAdding,
    canInsertWorkspaceQuickBlock,
    isWorkspacePageLocked,
    openDocumentTasks,
    documentTasks,
    visibleDocumentTasks,
    workspaceTaskFilterOptions,
    workspaceTaskAssigneeCandidates,
    newWorkspaceTask,
    newWorkspaceTaskAssignee,
    newWorkspaceTaskDueDate,
    workspaceTaskFilter,
    workspaceTaskEmptyLabel,
    documentTaskProgress,
    documentTaskSummaryLabel,
    canAddWorkspaceTask,
    workspaceTaskAdding,
    isWorkspaceTaskToggling,
    documentOutline,
    workspaceRelationCount,
    currentWorkspaceParentPage,
    currentWorkspaceChildPages,
    linkedWorkspaceDocuments,
    linkedWorkspaceDocumentEmptyLabel,
    workspaceBacklinks,
    workspaceBacklinkLoading,
    workspaceBacklinkError,
    workspaceBacklinkEmptyLabel,
    workspaceSubpageTitle,
    workspaceSubpageCreating,
    workspaceSubpageError,
    canStartWorkspaceSubpage,
    canCreateWorkspaceSubpage,
    workspaceRevisions,
    workspaceRevisionLoading,
    workspaceRevisionError,
    activeWorkspaceRevision,
    workspaceRevisionDiff,
    workspaceRevisionDiffSummary,
    workspaceRevisionDiffItems,
    workspaceRevisionPreviewLoading,
    workspaceRevisionRestoring,
    canRestoreWorkspaceRevision,
    workspaceRevisionReasonLabel,
    unresolvedWorkspaceComments,
    workspaceCommentFilters,
    workspaceCommentFilter,
    selectedBlockAnchor,
    commentAnchorLabel,
    showWorkspaceMentionMenu,
    canUseWorkspaceMentions,
    workspaceMentionCandidates,
    newWorkspaceComment,
    workspaceCommentSaving,
    workspaceCommentError,
    workspaceCommentLoading,
    workspaceComments,
    visibleWorkspaceComments,
    workspaceCommentEmptyLabel,
    workspaceCommentEditDraft,
    isWorkspaceCommentMentioningCurrentUser,
    canEditWorkspaceComment,
    isCommentUpdating,
    isCommentDeleting,
    isWorkspaceCommentEditing,
    isCommentResolving,
    workspaceAssets,
    workspaceAssetLoading,
    hasWorkspaceAssets,
    activeWorkspaceAssetId,
    getWorkspaceAssetBadge,
    isDeletingAsset,
    isSavingWorkspaceAsset,
    refreshWorkspacePageIndex = noop,
    openWorkspaceHomeMetric = noop,
    openWorkspaceHomeAttentionItem = noop,
    openWorkspaceHomeQueueItem = noop,
    openWorkspaceDocument = noop,
    openWorkspaceShare = noop,
    triggerFileSelect = noop,
    focusWorkspaceCommentComposer = noop,
    refreshWorkspaceMembers = noop,
    handleWorkspaceMemberRoleSelect = noop,
    removeWorkspaceMember = noop,
    focusWorkspaceInboxTask = noop,
    searchWorkspaceContents = noop,
    copyWorkspaceDocumentLink = noop,
    insertWorkspacePageLink = noop,
    toggleWorkspacePageTreeNode = noop,
    openWorkspaceTreeRename = noop,
    openWorkspaceTreeSubpageComposer = noop,
    openWorkspaceTreeMove = noop,
    renameWorkspaceTreePage = noop,
    cancelWorkspaceTreeRename = noop,
    moveWorkspaceTreePage = noop,
    cancelWorkspaceTreeMove = noop,
    createWorkspaceTreeSubpage = noop,
    cancelWorkspaceTreeSubpageComposer = noop,
    applyWorkspacePageIndexView = noop,
    removeWorkspacePageIndexView = noop,
    createWorkspacePageIndexView = noop,
    toggleVisibleWorkspacePageIndexSelection = noop,
    toggleWorkspacePageIndexRowSelection = noop,
    updateWorkspacePageIndexBulkProperties = noop,
    clearWorkspacePageIndexSelection = noop,
    updateWorkspacePageIndexRowProperties = noop,
    updateWorkspacePageIndexRowOwner = noop,
    updateWorkspacePageIndexRowTags = noop,
    setWorkspaceBoardDropTarget = noop,
    clearWorkspaceBoardDropTarget = noop,
    dropWorkspaceBoardCardStatus = noop,
    startWorkspaceBoardCardDrag = noop,
    clearWorkspaceBoardDrag = noop,
    moveWorkspaceBoardCardStatus = noop,
    toggleWorkspaceCalendarTask = noop,
    openWorkspaceCalendarItem = noop,
    toggleWorkspaceInboxTask = noop,
    insertWorkspaceQuickBlock = noop,
    addWorkspaceTask = noop,
    focusWorkspaceTaskItem = noop,
    toggleWorkspaceTaskItem = noop,
    focusWorkspaceOutlineItem = noop,
    refreshWorkspaceBacklinks = noop,
    openWorkspaceParentPage = noop,
    focusWorkspaceLinkedDocumentSource = noop,
    createWorkspaceSubpage = noop,
    refreshWorkspaceRevisions = noop,
    previewWorkspaceRevision = noop,
    restoreWorkspaceRevision = noop,
    clearWorkspaceCommentAnchor = noop,
    insertWorkspaceMention = noop,
    createWorkspaceComment = noop,
    startWorkspaceCommentEdit = noop,
    deleteWorkspaceComment = noop,
    focusWorkspaceCommentAnchor = noop,
    updateWorkspaceComment = noop,
    cancelWorkspaceCommentEdit = noop,
    toggleWorkspaceCommentResolved = noop,
    toggleWorkspaceAssetActions = noop,
    handleAssetDelete = noop,
    saveWorkspaceAssetToDrive = noop,
    downloadWorkspaceAsset = noop,
    registerSubpageInput = noop,
    registerCommentInput = noop,
  } = context

  const mutableValues = createWorkspaceFloatingPanelMutableValues(context)
  const setWorkspaceFloatingPanelValue = createWorkspaceFloatingPanelValueSetter(mutableValues)

  const workspaceFloatingPanelStackModel = computed(() => ({
    activeWorkspacePanelTab: unref(activeWorkspacePanelTab),
    isWorkspacePanelCollapsed: unref(isWorkspacePanelCollapsed),
    workspacePanelTabs: unref(workspacePanelTabs),
    isWorkspacePanelVisible,
    workspacePageIndexLoading: unref(workspacePageIndexLoading),
    workspaceHomeMetricCards: unref(workspaceHomeMetricCards),
    workspaceHomeAttentionItems: unref(workspaceHomeAttentionItems),
    workspaceHomeMyQueue: unref(workspaceHomeMyQueue),
    workspaceHomeRecentPages: unref(workspaceHomeRecentPages),
    documentBlockCount: unref(documentStats)?.blockCount ?? 0,
    workspaceSummaryCards: unref(workspaceSummaryCards),
    workspaceHealthItems: unref(workspaceHealthItems),
    activeUsers: unref(activeUsers),
    workspaceAccessRole: unref(workspaceAccessRole),
    workspaceShareStatusLabel: unref(workspaceShareStatusLabel),
    workspacePermissionItems: unref(workspacePermissionItems),
    canManageWorkspaceShare: unref(canManageWorkspaceShare),
    canManageAssets: unref(canManageAssets),
    canCommentOnWorkspace: unref(canCommentOnWorkspace),
    isValid: unref(isValid),
    isSaving: unref(isSaving),
    isEditorLoading: unref(isEditorLoading),
    workspaceShareButtonTitle: unref(workspaceShareButtonTitle),
    workspaceAssetUploading: unref(workspaceAssetUploading),
    workspaceId: unref(workspaceId),
    workspaceMemberSummaryLabel: unref(workspaceMemberSummaryLabel),
    workspaceMemberError: unref(workspaceMemberError),
    workspaceMemberLoading: unref(workspaceMemberLoading),
    workspaceMemberRows: unref(workspaceMemberRows),
    roleLabel,
    userInitial,
    isWorkspaceMemberBusy,
    workspaceWorkloadRows: unref(workspaceWorkloadRows),
    workspaceFullTextQuery: unref(workspaceFullTextQuery),
    workspaceFullTextResults: unref(workspaceFullTextResults),
    workspaceFullTextLoading: unref(workspaceFullTextLoading),
    workspaceFullTextError: unref(workspaceFullTextError),
    canSearchWorkspaceFullText: unref(canSearchWorkspaceFullText),
    canModifyWorkspacePage: unref(canModifyWorkspacePage),
    hasEditor: Boolean(unref(editorApi)),
    workspacePageTreeQuery: unref(workspacePageTreeQuery),
    workspaceTreeSubpageTitle: unref(workspaceTreeSubpageTitle),
    workspaceTreeRenameDraft: unref(workspaceTreeRenameDraft),
    workspaceTreeMoveTargetId: unref(workspaceTreeMoveTargetId),
    workspacePageTreeVisibleRows: unref(workspacePageTreeVisibleRows),
    workspacePageTreeEmptyLabel: unref(workspacePageTreeEmptyLabel),
    workspacePageTreeCollapsedIdSet: unref(workspacePageTreeCollapsedIdSet),
    workspaceTreeSubpageError: unref(workspaceTreeSubpageError),
    workspaceTreeRenameError: unref(workspaceTreeRenameError),
    workspaceTreeMoveError: unref(workspaceTreeMoveError),
    workspaceTreeSubpageCreatingId: unref(workspaceTreeSubpageCreatingId),
    workspaceTreeSubpageComposerParentId: unref(workspaceTreeSubpageComposerParentId),
    workspaceTreeRenamingId: unref(workspaceTreeRenamingId),
    workspaceTreeRenameSavingId: unref(workspaceTreeRenameSavingId),
    workspaceTreeMovingId: unref(workspaceTreeMovingId),
    workspaceTreeMoveSavingId: unref(workspaceTreeMoveSavingId),
    isWorkspaceDocumentLinkCopied,
    workspaceTreeMoveTargetOptions: unref(workspaceTreeMoveTargetOptions),
    canApplyWorkspaceTreeMove: unref(canApplyWorkspaceTreeMove),
    workspacePageIndexError: unref(workspacePageIndexError),
    workspacePageIndexFilter: unref(workspacePageIndexFilter),
    workspacePageIndexFilterOptions: unref(workspacePageIndexFilterOptions),
    workspacePageIndexQuery: unref(workspacePageIndexQuery),
    workspacePageIndexSort: unref(workspacePageIndexSort),
    workspacePageIndexSortOptions: unref(workspacePageIndexSortOptions),
    workspacePageIndexOwnerFilter: unref(workspacePageIndexOwnerFilter),
    workspacePageIndexOwnerFilterOptions: unref(workspacePageIndexOwnerFilterOptions),
    workspacePageIndexTagFilter: unref(workspacePageIndexTagFilter),
    workspacePageIndexTagOptions: unref(workspacePageIndexTagOptions),
    workspacePageIndexViews: unref(workspacePageIndexViews),
    activeWorkspacePageIndexView: unref(activeWorkspacePageIndexView),
    workspacePageIndexViewName: unref(workspacePageIndexViewName),
    canCreateWorkspacePageIndexView: unref(canCreateWorkspacePageIndexView),
    visibleEditableWorkspacePageIndexRows: unref(visibleEditableWorkspacePageIndexRows),
    selectedWorkspacePageIndexRows: unref(selectedWorkspacePageIndexRows),
    areAllVisibleWorkspacePageIndexRowsSelected: unref(areAllVisibleWorkspacePageIndexRowsSelected),
    canApplyWorkspacePageIndexBulkUpdate: unref(canApplyWorkspacePageIndexBulkUpdate),
    workspacePageIndexBulkStatus: unref(workspacePageIndexBulkStatus),
    workspacePageIndexBulkPriority: unref(workspacePageIndexBulkPriority),
    workspacePageIndexBulkOwnerEmail: unref(workspacePageIndexBulkOwnerEmail),
    workspacePageIndexBulkDueDate: unref(workspacePageIndexBulkDueDate),
    workspacePageIndexBulkClearDueDate: unref(workspacePageIndexBulkClearDueDate),
    workspacePageIndexBulkUpdating: unref(workspacePageIndexBulkUpdating),
    workspacePropertyOwnerCandidates: unref(workspacePropertyOwnerCandidates),
    workspacePropertyStatusOptions,
    workspacePropertyPriorityOptions,
    visibleWorkspacePageIndexRows: unref(visibleWorkspacePageIndexRows),
    workspacePageIndexOwnerOptions: unref(workspacePageIndexOwnerOptions),
    isWorkspacePageIndexRowSelected,
    isRowUpdating: isWorkspacePageIndexRowUpdating,
    isWorkspacePageIndexRowUpdating,
    workspacePageIndexViewSummary: unref(workspacePageIndexViewSummary),
    workspaceBoardRows: unref(workspaceBoardRows),
    workspaceBoardColumns: unref(workspaceBoardColumns),
    workspaceBoardDraggingId: unref(workspaceBoardDraggingId),
    workspaceBoardDragOverStatus: unref(workspaceBoardDragOverStatus),
    workspaceTimelineFilter: unref(workspaceTimelineFilter),
    workspaceTimelineFilterOptions: unref(workspaceTimelineFilterOptions),
    workspaceTimelineRange: unref(workspaceTimelineRange),
    workspaceTimelineGroups: unref(workspaceTimelineGroups),
    workspaceTimelineEmptyLabel: unref(workspaceTimelineEmptyLabel),
    workspaceTimelineItemStyle,
    workspaceCalendarFilter: unref(workspaceCalendarFilter),
    workspaceCalendarFilterOptions: unref(workspaceCalendarFilterOptions),
    workspaceCalendarGroups: unref(workspaceCalendarGroups),
    workspaceCalendarEmptyLabel: unref(workspaceCalendarEmptyLabel),
    todayKey: workspaceTaskTodayKey(),
    inboxOpenTaskCount: unref(openWorkspaceIndexedTasks)?.length ?? 0,
    workspaceInboxFilterOptions: unref(workspaceInboxFilterOptions),
    workspaceInboxFilter: unref(workspaceInboxFilter),
    visibleWorkspaceInboxTasks: unref(visibleWorkspaceInboxTasks),
    workspaceInboxEmptyLabel: unref(workspaceInboxEmptyLabel),
    isWorkspaceInboxTaskToggling,
    workspaceActivityItems: unref(workspaceActivityItems),
    workspaceQuickBlockOptions,
    workspaceQuickBlockText: unref(workspaceQuickBlockText),
    workspaceQuickBlockAdding: unref(workspaceQuickBlockAdding),
    canInsertWorkspaceQuickBlock: unref(canInsertWorkspaceQuickBlock),
    isWorkspacePageLocked: unref(isWorkspacePageLocked),
    openDocumentTasks: unref(openDocumentTasks),
    documentTasks: unref(documentTasks),
    visibleDocumentTasks: unref(visibleDocumentTasks),
    workspaceTaskFilterOptions: unref(workspaceTaskFilterOptions),
    workspaceTaskAssigneeCandidates: unref(workspaceTaskAssigneeCandidates),
    newWorkspaceTask: unref(newWorkspaceTask),
    newWorkspaceTaskAssignee: unref(newWorkspaceTaskAssignee),
    newWorkspaceTaskDueDate: unref(newWorkspaceTaskDueDate),
    workspaceTaskFilter: unref(workspaceTaskFilter),
    workspaceTaskEmptyLabel: unref(workspaceTaskEmptyLabel),
    documentTaskProgress: unref(documentTaskProgress),
    documentTaskSummaryLabel: unref(documentTaskSummaryLabel),
    canAddWorkspaceTask: unref(canAddWorkspaceTask),
    workspaceTaskAdding: unref(workspaceTaskAdding),
    isWorkspaceTaskToggling,
    documentOutline: unref(documentOutline),
    workspaceRelationCount: unref(workspaceRelationCount),
    currentWorkspaceParentPage: unref(currentWorkspaceParentPage),
    currentWorkspaceChildPages: unref(currentWorkspaceChildPages),
    linkedWorkspaceDocuments: unref(linkedWorkspaceDocuments),
    linkedWorkspaceDocumentEmptyLabel: unref(linkedWorkspaceDocumentEmptyLabel),
    workspaceBacklinks: unref(workspaceBacklinks),
    workspaceBacklinkLoading: unref(workspaceBacklinkLoading),
    workspaceBacklinkError: unref(workspaceBacklinkError),
    workspaceBacklinkEmptyLabel: unref(workspaceBacklinkEmptyLabel),
    workspaceSubpageTitle: unref(workspaceSubpageTitle),
    workspaceSubpageCreating: unref(workspaceSubpageCreating),
    workspaceSubpageError: unref(workspaceSubpageError),
    canStartWorkspaceSubpage: unref(canStartWorkspaceSubpage),
    canCreateWorkspaceSubpage: unref(canCreateWorkspaceSubpage),
    workspaceRevisions: unref(workspaceRevisions),
    workspaceRevisionLoading: unref(workspaceRevisionLoading),
    workspaceRevisionError: unref(workspaceRevisionError),
    activeWorkspaceRevision: unref(activeWorkspaceRevision),
    workspaceRevisionDiff: unref(workspaceRevisionDiff),
    workspaceRevisionDiffSummary: unref(workspaceRevisionDiffSummary),
    workspaceRevisionDiffItems: unref(workspaceRevisionDiffItems),
    workspaceRevisionPreviewLoading: unref(workspaceRevisionPreviewLoading),
    workspaceRevisionRestoring: unref(workspaceRevisionRestoring),
    canRestoreWorkspaceRevision: unref(canRestoreWorkspaceRevision),
    workspaceRevisionReasonLabel,
    unresolvedWorkspaceComments: unref(unresolvedWorkspaceComments),
    workspaceCommentFilters: unref(workspaceCommentFilters),
    workspaceCommentFilter: unref(workspaceCommentFilter),
    selectedBlockAnchor: unref(selectedBlockAnchor),
    commentAnchorLabel: unref(commentAnchorLabel),
    showWorkspaceMentionMenu: unref(showWorkspaceMentionMenu),
    canUseWorkspaceMentions: unref(canUseWorkspaceMentions),
    workspaceMentionCandidates: unref(workspaceMentionCandidates),
    newWorkspaceComment: unref(newWorkspaceComment),
    workspaceCommentSaving: unref(workspaceCommentSaving),
    workspaceCommentError: unref(workspaceCommentError),
    workspaceCommentLoading: unref(workspaceCommentLoading),
    workspaceComments: unref(workspaceComments),
    visibleWorkspaceComments: unref(visibleWorkspaceComments),
    workspaceCommentEmptyLabel: unref(workspaceCommentEmptyLabel),
    workspaceCommentEditDraft: unref(workspaceCommentEditDraft),
    isWorkspaceCommentMentioningCurrentUser,
    canEditWorkspaceComment,
    isCommentUpdating,
    isCommentDeleting,
    isWorkspaceCommentEditing,
    isCommentResolving,
    workspaceAssets: unref(workspaceAssets),
    workspaceAssetLoading: unref(workspaceAssetLoading),
    hasWorkspaceAssets: unref(hasWorkspaceAssets),
    activeWorkspaceAssetId: unref(activeWorkspaceAssetId),
    getWorkspaceAssetBadge,
    isDeletingAsset,
    isSavingWorkspaceAsset,
  }))

  const workspaceFloatingPanelStackActions = {
    setValue: setWorkspaceFloatingPanelValue,
    refreshWorkspacePageIndex: () => refreshWorkspacePageIndex(),
    openWorkspaceHomeMetric,
    openWorkspaceHomeAttentionItem,
    openWorkspaceHomeQueueItem,
    openWorkspaceDocument,
    openWorkspaceShare,
    triggerFileSelect,
    focusWorkspaceCommentComposer,
    refreshWorkspaceMembers: () => refreshWorkspaceMembers(),
    handleWorkspaceMemberRoleSelect,
    removeWorkspaceMember,
    focusWorkspaceInboxTask,
    searchWorkspaceContents,
    copyWorkspaceDocumentLink,
    insertWorkspacePageLink,
    toggleWorkspacePageTreeNode,
    openWorkspaceTreeRename,
    openWorkspaceTreeSubpageComposer,
    openWorkspaceTreeMove,
    renameWorkspaceTreePage,
    cancelWorkspaceTreeRename,
    moveWorkspaceTreePage,
    cancelWorkspaceTreeMove,
    createWorkspaceTreeSubpage,
    cancelWorkspaceTreeSubpageComposer,
    applyWorkspacePageIndexView,
    removeWorkspacePageIndexView,
    createWorkspacePageIndexView,
    toggleVisibleWorkspacePageIndexSelection,
    toggleWorkspacePageIndexRowSelection,
    updateWorkspacePageIndexBulkProperties,
    clearWorkspacePageIndexSelection,
    updateWorkspacePageIndexRowStatus: (row, status) => updateWorkspacePageIndexRowProperties(row, { status }),
    updateWorkspacePageIndexRowPriority: (row, priority) => updateWorkspacePageIndexRowProperties(row, { priority }),
    updateWorkspacePageIndexRowOwner,
    updateWorkspacePageIndexRowDueDate: (row, dueDate) => updateWorkspacePageIndexRowProperties(row, { dueDate }),
    updateWorkspacePageIndexRowTags,
    setWorkspaceBoardDropTarget,
    clearWorkspaceBoardDropTarget,
    dropWorkspaceBoardCardStatus,
    startWorkspaceBoardCardDrag,
    clearWorkspaceBoardDrag,
    moveWorkspaceBoardCardStatus,
    toggleWorkspaceCalendarTask,
    openWorkspaceCalendarItem,
    toggleWorkspaceInboxTask,
    insertWorkspaceQuickBlock,
    addWorkspaceTask,
    focusWorkspaceTaskItem,
    toggleWorkspaceTaskItem,
    focusWorkspaceOutlineItem,
    refreshWorkspaceBacklinks: () => refreshWorkspaceBacklinks(),
    openWorkspaceParentPage,
    focusWorkspaceLinkedDocumentSource,
    createWorkspaceSubpage,
    refreshWorkspaceRevisions: () => refreshWorkspaceRevisions(),
    previewWorkspaceRevision,
    restoreWorkspaceRevision,
    clearWorkspaceCommentAnchor,
    insertWorkspaceMention,
    createWorkspaceComment,
    startWorkspaceCommentEdit,
    deleteWorkspaceComment,
    focusWorkspaceCommentAnchor,
    updateWorkspaceComment,
    cancelWorkspaceCommentEdit,
    toggleWorkspaceCommentResolved,
    toggleWorkspaceAssetActions,
    handleAssetDelete,
    saveWorkspaceAssetToDrive,
    downloadWorkspaceAsset,
    registerSubpageInput,
    registerCommentInput,
  }

  return {
    workspaceFloatingPanelStackModel,
    workspaceFloatingPanelStackActions,
    setWorkspaceFloatingPanelValue,
  }
}
