import { useWorkspacePeopleTaskSetup } from './useWorkspacePeopleTaskSetup.js'

export const createWorkspacePeopleExperienceGroups = ({
  platform = {},
  workspaceState = {},
  options = {},
  presence = {},
  user = {},
  planning = {},
  document = {},
  assets = {},
  comments = {},
  revisions = {},
  access = {},
  persistence = {},
  refreshers = {},
  focus = {},
  ui = {},
  formatters = {},
} = {}) => ({
  platform,
  state: {
    workspaceMembers: workspaceState.workspaceMembers,
    workspaceMemberRefreshedAt: workspaceState.workspaceMemberRefreshedAt,
    lastSavedAt: workspaceState.lastSavedAt,
    newWorkspaceTaskAssignee: workspaceState.newWorkspaceTaskAssignee,
    workspacePropertyTagsInput: workspaceState.workspacePropertyTagsInput,
    workspacePropertyOwnerEmail: workspaceState.workspacePropertyOwnerEmail,
    workspacePropertyOwnerName: workspaceState.workspacePropertyOwnerName,
    workspacePropertyStatus: workspaceState.workspacePropertyStatus,
    workspacePropertyPriority: workspaceState.workspacePropertyPriority,
    workspacePropertyCoverColor: workspaceState.workspacePropertyCoverColor,
    togglingWorkspaceTaskIds: workspaceState.togglingWorkspaceTaskIds,
    togglingWorkspaceInboxTaskIds: workspaceState.togglingWorkspaceInboxTaskIds,
    editorApi: workspaceState.editorApi,
    currentWorkspaceKey: planning.currentWorkspaceKey,
    newWorkspaceTask: workspaceState.newWorkspaceTask,
    newWorkspaceTaskDueDate: workspaceState.newWorkspaceTaskDueDate,
    workspaceTaskAdding: workspaceState.workspaceTaskAdding,
  },
  options: {
    quickBlockOptions: options.quickBlockOptions ?? [],
    statusOptions: options.statusOptions ?? [],
    priorityOptions: options.priorityOptions ?? [],
    coverColorOptions: options.coverColorOptions ?? [],
  },
  presence,
  user,
  planning: {
    workspacePageIndexRows: workspaceState.workspacePageIndexRows,
    workspaceIndexedTasks: planning.workspaceIndexedTasks,
    openWorkspaceIndexedTasks: planning.openWorkspaceIndexedTasks,
    myWorkspaceIndexedTasks: planning.myWorkspaceIndexedTasks,
    overdueWorkspaceCalendarItems: planning.overdueWorkspaceCalendarItems,
    workspaceFullTextResults: planning.workspaceFullTextResults,
    workspaceRelationCount: planning.workspaceRelationCount,
  },
  document,
  assets: {
    workspaceAssets: workspaceState.workspaceAssets,
    workspaceImages: assets.workspaceImages,
    workspaceFiles: assets.workspaceFiles,
  },
  comments: {
    workspaceComments: workspaceState.workspaceComments,
    unresolvedWorkspaceComments: comments.unresolvedWorkspaceComments,
    resolvedWorkspaceComments: comments.resolvedWorkspaceComments,
    mentionedWorkspaceComments: comments.mentionedWorkspaceComments,
  },
  revisions,
  access,
  persistence,
  refreshers,
  focus,
  ui,
  formatters,
})

export const useWorkspacePeopleExperienceSetup = (groups = {}) =>
  useWorkspacePeopleTaskSetup(createWorkspacePeopleExperienceGroups(groups))
