import { useWorkspaceDocumentOperationsSetup } from './useWorkspaceDocumentOperationsSetup.js'

export const createWorkspaceDocumentOperationsExperienceGroups = ({
  platform = {},
  workspaceState = {},
  documentState = {},
  derived = {},
  people = {},
  access = {},
  propertyOptions = {},
  preferences = {},
  workspace = {},
  guards = {},
  editor = {},
  refreshers = {},
  metadata = {},
  normalizers = {},
  ui = {},
  messages = {},
  documentIdFor,
} = {}) => ({
  platform,
  state: {
    currentWorkspaceKey: derived.currentWorkspaceKey,
    editorApi: workspaceState.editorApi,
    isEditorLoading: workspaceState.isEditorLoading,
    workspaceMarkdownExporting: workspaceState.workspaceMarkdownExporting,
    title: workspaceState.title,
    workspacePropertyStatusOption: people.workspacePropertyStatusOption,
    workspacePropertyPriorityOption: people.workspacePropertyPriorityOption,
    workspacePropertyOwnerEmail: workspaceState.workspacePropertyOwnerEmail,
    workspacePropertyOwnerName: workspaceState.workspacePropertyOwnerName,
    workspacePropertyDueDate: workspaceState.workspacePropertyDueDate,
    workspacePropertyTags: people.workspacePropertyTags,
    workspaceId: workspaceState.workspaceId,
    workspaceAccessRole: workspaceState.workspaceAccessRole,
    workspaceSubpageInput: workspaceState.workspaceSubpageInput,
    workspaceSubpageTitle: workspaceState.workspaceSubpageTitle,
    workspaceSubpageCreating: workspaceState.workspaceSubpageCreating,
    workspaceSubpageError: workspaceState.workspaceSubpageError,
    isWorkspacePanelCollapsed: workspaceState.isWorkspacePanelCollapsed,
    activeWorkspacePanelTab: workspaceState.activeWorkspacePanelTab,
    workspaceDocumentSections: documentState.workspaceDocumentSections,
    workspaceSectionNameDraft: workspaceState.workspaceSectionNameDraft,
    workspaceSectionEditingId: workspaceState.workspaceSectionEditingId,
    workspaceSectionEditDraft: workspaceState.workspaceSectionEditDraft,
    workspaceSectionEditInput: workspaceState.workspaceSectionEditInput,
    workspaceRevisions: workspaceState.workspaceRevisions,
    workspaceRevisionLoading: workspaceState.workspaceRevisionLoading,
    workspaceRevisionError: workspaceState.workspaceRevisionError,
    activeWorkspaceRevision: workspaceState.activeWorkspaceRevision,
    workspaceRevisionDiff: workspaceState.workspaceRevisionDiff,
    workspaceRevisionPreviewLoading: workspaceState.workspaceRevisionPreviewLoading,
    workspaceRevisionRestoring: workspaceState.workspaceRevisionRestoring,
    hasUnsavedChanges: derived.hasUnsavedChanges,
    titleDirty: workspaceState.titleDirty,
    workspaceShareStatus: workspaceState.workspaceShareStatus,
    workspaceUuid: workspaceState.workspaceUuid,
    saveState: workspaceState.saveState,
    lastSavedAt: workspaceState.lastSavedAt,
  },
  access,
  propertyOptions,
  preferences: {
    favoriteWorkspaceDocumentIds: documentState.favoriteWorkspaceDocumentIds,
    trackRecentWorkspaceDocument: preferences.trackRecentWorkspaceDocument,
    persistFavoriteWorkspaceDocuments: preferences.persistFavoriteWorkspaceDocuments,
    persistWorkspaceDocumentSections: preferences.persistWorkspaceDocumentSections,
  },
  workspace,
  guards,
  editor,
  refreshers,
  metadata,
  normalizers,
  ui,
  messages,
  documentIdFor,
})

export const useWorkspaceDocumentOperationsExperienceSetup = (groups = {}) =>
  useWorkspaceDocumentOperationsSetup(createWorkspaceDocumentOperationsExperienceGroups(groups))
