import { useWorkspaceEditorInteractionSetup } from './useWorkspaceEditorInteractionSetup.js'

export const createWorkspaceEditorExperienceGroups = ({
  platform = {},
  workspaceState = {},
  derived = {},
  options = {},
  access = {},
  user = {},
  persistence = {},
  assets = {},
  comments = {},
  revisions = {},
  ui = {},
} = {}) => ({
  platform,
  state: {
    editorApi: workspaceState.editorApi,
    isEditorLoading: workspaceState.isEditorLoading,
    hasUnsavedChanges: derived.hasUnsavedChanges,
    saveState: workspaceState.saveState,
    workspaceSubpageCreating: workspaceState.workspaceSubpageCreating,
    workspaceSubpageTitle: workspaceState.workspaceSubpageTitle,
    workspaceQuickBlockAdding: workspaceState.workspaceQuickBlockAdding,
    workspaceQuickBlockText: workspaceState.workspaceQuickBlockText,
    workspaceInlineQuickBlockText: workspaceState.workspaceInlineQuickBlockText,
    activeWorkspacePanelTab: workspaceState.activeWorkspacePanelTab,
    workspacePageLocked: workspaceState.workspacePageLocked,
    title: workspaceState.title,
    titleDirty: workspaceState.titleDirty,
    workspaceTemplateApplying: workspaceState.workspaceTemplateApplying,
    workspaceTemplateApplied: workspaceState.workspaceTemplateApplied,
    documentTasks: derived.documentTasks,
    workspaceTaskFilter: workspaceState.workspaceTaskFilter,
    workspaceTaskAdding: workspaceState.workspaceTaskAdding,
    newWorkspaceTask: workspaceState.newWorkspaceTask,
    workspaceAssets: workspaceState.workspaceAssets,
    savingWorkspaceAssetIds: workspaceState.savingWorkspaceAssetIds,
    workspaceId: workspaceState.workspaceId,
    workspaceAssetUploading: workspaceState.workspaceAssetUploading,
    workspaceAssetError: workspaceState.workspaceAssetError,
    activeWorkspaceAssetId: workspaceState.activeWorkspaceAssetId,
    deletingAssetIds: workspaceState.deletingAssetIds,
    imageInput: workspaceState.imageInput,
    fileInput: workspaceState.fileInput,
    workspaceComments: workspaceState.workspaceComments,
    selectedBlockAnchor: derived.selectedBlockAnchor,
    workspaceCommentFilter: workspaceState.workspaceCommentFilter,
    workspaceRevisions: workspaceState.workspaceRevisions,
    activeWorkspaceRevision: workspaceState.activeWorkspaceRevision,
    workspaceRevisionDiff: workspaceState.workspaceRevisionDiff,
    workspaceCommentSaving: workspaceState.workspaceCommentSaving,
    workspaceCommentError: workspaceState.workspaceCommentError,
    workspaceCommentEditingId: workspaceState.workspaceCommentEditingId,
    workspaceCommentEditDraft: workspaceState.workspaceCommentEditDraft,
    newWorkspaceComment: workspaceState.newWorkspaceComment,
    resolvingCommentIds: workspaceState.resolvingCommentIds,
    deletingCommentIds: workspaceState.deletingCommentIds,
    updatingCommentIds: workspaceState.updatingCommentIds,
    isValid: derived.isValid,
  },
  options: {
    quickBlockOptions: options.quickBlockOptions ?? [],
  },
  access,
  user,
  persistence,
  assets,
  comments,
  revisions,
  ui,
})

export const useWorkspaceEditorExperienceSetup = (groups = {}) =>
  useWorkspaceEditorInteractionSetup(createWorkspaceEditorExperienceGroups(groups))
