import { computed, unref } from 'vue'

const noop = () => {}

const call = (fn, ...args) => (typeof fn === 'function' ? fn(...args) : undefined)

export const createWorkspaceMainLayoutValueSetter = (mutableValues = {}) => (key, value) => {
  const target = mutableValues[key]
  if (target && typeof target === 'object' && 'value' in target) {
    target.value = value
  }
}

export const createWorkspaceMainLayoutMutableValues = ({
  workspaceDocumentQuery,
  workspaceSectionNameDraft,
  workspaceSectionEditDraft,
  workspacePropertyIcon,
  workspacePropertyCoverColor,
  workspacePropertyStatus,
  workspacePropertyPriority,
  workspacePropertyOwnerEmail,
  workspacePropertyDueDate,
  workspacePropertyTagsInput,
  showUserList,
  openRoleDropdownId,
  isWorkspacePanelCollapsed,
  workspaceInlineQuickBlockText,
  workspaceSectionEditInput,
  imageInput,
  fileInput,
  editorHolder,
} = {}) => ({
  workspaceDocumentQuery,
  workspaceSectionNameDraft,
  workspaceSectionEditDraft,
  workspacePropertyIcon,
  workspacePropertyCoverColor,
  workspacePropertyStatus,
  workspacePropertyPriority,
  workspacePropertyOwnerEmail,
  workspacePropertyDueDate,
  workspacePropertyTagsInput,
  showUserList,
  openRoleDropdownId,
  isWorkspacePanelCollapsed,
  workspaceInlineQuickBlockText,
  workspaceSectionEditInput,
  imageInput,
  fileInput,
  editorHolder,
})

export const useWorkspaceMainLayoutBridge = (context = {}) => {
  const mutableValues = createWorkspaceMainLayoutMutableValues(context)
  const setValue = context.setValue ?? createWorkspaceMainLayoutValueSetter(mutableValues)

  const workspaceMainLayoutModel = computed(() => ({
    documentQuery: unref(context.workspaceDocumentQuery),
    sectionNameDraft: unref(context.workspaceSectionNameDraft),
    sectionEditDraft: unref(context.workspaceSectionEditDraft),
    sectionEditingId: unref(context.workspaceSectionEditingId),
    documentsLoading: unref(context.workspaceDocumentsLoading),
    currentWorkspaceKey: unref(context.currentWorkspaceKey),
    favoriteDocuments: unref(context.favoriteWorkspaceDocuments),
    recentDocuments: unref(context.recentWorkspaceDocuments),
    documentSections: unref(context.workspaceDocumentSections),
    visibleSectionViews: unref(context.visibleWorkspaceDocumentSectionViews),
    sectionedDocumentCount: unref(context.workspaceSectionedDocumentCount),
    personalDocuments: unref(context.unsectionedPersonalWorkspaceDocuments),
    sharedDocuments: unref(context.unsectionedSharedWorkspaceDocuments),
    canModifyPage: unref(context.canModifyWorkspacePage),
    hasEditor: unref(context.editorApi) != null,
    isDocumentFavorite: context.isWorkspaceDocumentFavorite ?? noop,
    documentSectionId: context.workspaceDocumentSectionId ?? noop,
    isDocumentActionLoading: context.isDocumentActionLoading ?? noop,
    icon: unref(context.workspacePropertyIcon),
    coverColor: unref(context.workspacePropertyCoverColor),
    status: unref(context.workspacePropertyStatus),
    priority: unref(context.workspacePropertyPriority),
    ownerEmail: unref(context.workspacePropertyOwnerEmail),
    dueDate: unref(context.workspacePropertyDueDate),
    tagsInput: unref(context.workspacePropertyTagsInput),
    presenceOpen: unref(context.showUserList),
    openRoleDropdownId: unref(context.openRoleDropdownId),
    panelCollapsed: unref(context.isWorkspacePanelCollapsed),
    inlineQuickBlockText: unref(context.workspaceInlineQuickBlockText),
    title: unref(context.title),
    breadcrumbs: unref(context.workspacePageBreadcrumbTrail),
    coverColorOption: unref(context.workspacePropertyCoverColorOption),
    statusOption: unref(context.workspacePropertyStatusOption),
    priorityOption: unref(context.workspacePropertyPriorityOption),
    ownerCandidates: unref(context.workspacePropertyOwnerCandidates),
    tags: unref(context.workspacePropertyTags),
    saveStatusClass: unref(context.saveStatusClass),
    saveStatusLabel: unref(context.saveStatusLabel),
    realtimeStatusClass: unref(context.realtimeStatusClass),
    realtimeStatusLabel: unref(context.realtimeStatusLabel),
    shareStatusClass: unref(context.workspaceShareStatusClass),
    shareStatusLabel: unref(context.workspaceShareStatusLabel),
    accessRoleLabel: call(context.roleLabel, unref(context.workspaceAccessRole)),
    isPageLocked: unref(context.isWorkspacePageLocked),
    lockStatusLabel: unref(context.workspaceLockStatusLabel),
    workspaceId: unref(context.workspaceId),
    linkCopied: Boolean(unref(context.workspaceDocumentLinkCopiedId)),
    activeUserPreview: unref(context.activeUserPreview),
    extraActiveUserCount: unref(context.extraActiveUserCount),
    activeUsers: unref(context.activeUsers),
    presenceSummaryLabel: unref(context.presenceSummaryLabel),
    canManageShare: unref(context.canManageWorkspaceShare),
    canEditWorkspace: unref(context.canEditWorkspace),
    isValid: unref(context.isValid),
    isSaving: unref(context.isSaving),
    isEditorLoading: unref(context.isEditorLoading),
    canFavoriteDocument: unref(context.canFavoriteCurrentWorkspaceDocument),
    isFavorite: unref(context.isCurrentWorkspaceDocumentFavorite),
    favoriteTitle: unref(context.currentWorkspaceFavoriteTitle),
    lockButtonTitle: unref(context.workspaceLockButtonTitle),
    canCopyLink: unref(context.canCopyCurrentWorkspaceDocumentLink),
    isLinkCopied: call(context.isWorkspaceDocumentLinkCopied, unref(context.currentWorkspaceLinkDocument)),
    canExportMarkdown: unref(context.canExportWorkspaceMarkdown),
    markdownExporting: unref(context.workspaceMarkdownExporting),
    shareButtonTitle: unref(context.workspaceShareButtonTitle),
    assets: unref(context.workspaceAssets),
    images: unref(context.workspaceImages),
    files: unref(context.workspaceFiles),
    assetLoading: unref(context.workspaceAssetLoading),
    assetUploading: unref(context.workspaceAssetUploading),
    assetError: unref(context.workspaceAssetError),
    canManageAssets: unref(context.canManageAssets),
    isDeletingAsset: unref(context.isDeletingAsset),
    canShowTemplates: unref(context.canShowWorkspaceTemplates),
    templates: unref(context.workspaceTemplates),
    templateApplying: unref(context.workspaceTemplateApplying),
    inlineQuickBlockOptions: unref(context.workspaceInlineQuickBlockOptions),
    canInsertQuickBlock: unref(context.canInsertWorkspaceQuickBlock),
    quickBlockAdding: unref(context.workspaceQuickBlockAdding),
    remoteCursors: unref(context.remoteCursors),
  }))

  const workspaceMainLayoutActions = {
    setValue,
    registerSectionEditInput: (value) => setValue('workspaceSectionEditInput', value),
    openWorkspaceCommandPalette: (...args) => call(context.openWorkspaceCommandPalette, ...args),
    createWorkspaceDocument: (...args) => call(context.createWorkspaceDocument, ...args),
    createWorkspaceDocumentSection: (...args) => call(context.createWorkspaceDocumentSection, ...args),
    saveWorkspaceDocumentSectionRename: (...args) => call(context.saveWorkspaceDocumentSectionRename, ...args),
    cancelWorkspaceDocumentSectionRename: (...args) => call(context.cancelWorkspaceDocumentSectionRename, ...args),
    toggleWorkspaceDocumentSection: (...args) => call(context.toggleWorkspaceDocumentSection, ...args),
    startWorkspaceDocumentSectionRename: (...args) => call(context.startWorkspaceDocumentSectionRename, ...args),
    removeWorkspaceDocumentSection: (...args) => call(context.removeWorkspaceDocumentSection, ...args),
    openWorkspaceDocument: (...args) => call(context.openWorkspaceDocument, ...args),
    toggleFavoriteWorkspaceDocument: (...args) => call(context.toggleFavoriteWorkspaceDocument, ...args),
    moveWorkspaceDocumentToSection: (...args) => call(context.moveWorkspaceDocumentToSection, ...args),
    insertWorkspacePageLink: (...args) => call(context.insertWorkspacePageLink, ...args),
    copyWorkspaceDocumentLink: (...args) => call(context.copyWorkspaceDocumentLink, ...args),
    duplicateWorkspaceDocument: (...args) => call(context.duplicateWorkspaceDocument, ...args),
    removeWorkspaceDocument: (...args) => call(context.removeWorkspaceDocument, ...args),
    normalizeWorkspacePageIcon: () => setValue(
      'workspacePropertyIcon',
      call(context.normalizeWorkspacePageIcon, unref(context.workspacePropertyIcon)),
    ),
    handleTitleInput: (...args) => call(context.handleTitleInput, ...args),
    handleRoleAction: (...args) => call(context.handleRoleAction, ...args),
    handleSave: (...args) => call(context.handleSave, ...args),
    toggleCurrentWorkspaceDocumentFavorite: (...args) => call(context.toggleCurrentWorkspaceDocumentFavorite, ...args),
    toggleWorkspacePageLock: (...args) => call(context.toggleWorkspacePageLock, ...args),
    copyCurrentWorkspaceDocumentLink: () => call(
      context.copyWorkspaceDocumentLink,
      unref(context.currentWorkspaceLinkDocument),
    ),
    exportWorkspaceMarkdown: (...args) => call(context.exportWorkspaceMarkdown, ...args),
    openWorkspaceShare: (...args) => call(context.openWorkspaceShare, ...args),
    handleAssetSelection: (...args) => call(context.handleAssetSelection, ...args),
    triggerImageSelect: (...args) => call(context.triggerImageSelect, ...args),
    triggerFileSelect: (...args) => call(context.triggerFileSelect, ...args),
    handleAssetDelete: (...args) => call(context.handleAssetDelete, ...args),
    downloadWorkspaceAsset: (...args) => call(context.downloadWorkspaceAsset, ...args),
    applyWorkspaceTemplate: (...args) => call(context.applyWorkspaceTemplate, ...args),
    insertWorkspaceInlineQuickBlock: (...args) => call(context.insertWorkspaceInlineQuickBlock, ...args),
    registerImageInput: (value) => setValue('imageInput', value),
    registerFileInput: (value) => setValue('fileInput', value),
    registerEditorHolder: (value) => setValue('editorHolder', value),
  }

  return {
    workspaceMainLayoutModel,
    workspaceMainLayoutActions,
  }
}
