import { useWorkspaceDocumentLoader } from './useWorkspaceDocumentLoader.js'
import { useWorkspaceEditorSetup } from './useWorkspaceEditorSetup.js'
import { useWorkspaceLifecycleBindings } from './useWorkspaceLifecycleBindings.js'
import { useWorkspaceLifecycleWatchers } from './useWorkspaceLifecycleWatchers.js'
import { useWorkspaceSseRoleChange } from './useWorkspaceSseRoleChange.js'
import { useWorkspaceThemeSync } from './useWorkspaceThemeSync.js'

export const useWorkspaceRuntimeLifecycle = ({
  route,
  router,
  api,
  authStore,
  handleRouteLeave,
  handleRouteUpdate,
  handleBeforeUnload,
  handleWorkspaceGlobalKeydown,
  closeRoleDropdown,
  showWorkspaceNotice,
  allowNextRouteLeave,
  allowNextWindowUnload,
  editorHolder,
  editorApi,
  isEditorLoading,
  saveState,
  saveError,
  lastSavedAt,
  title,
  titleDirty,
  workspaceTemplateApplied,
  workspaceTemplateApplying,
  workspaceId,
  workspaceAccessRole,
  workspaceShareStatus,
  workspaceUuid,
  showWorkspaceShareModal,
  shouldWorkspaceEditorReadOnly,
  currentWorkspaceProperties,
  workspaceParentPageId,
  workspaceParentPageTitle,
  workspaceDocumentById,
  clearAutoSaveTimer,
  resetLeaveGuardBypass,
  normalizeWorkspaceShareStatus,
  trackRecentWorkspaceDocument,
  applyWorkspaceProperties,
  applyWorkspaceParentPage,
  extractWorkspacePropertiesFromContents,
  extractWorkspaceParentFromContents,
  refreshWorkspaceAssets,
  refreshWorkspaceComments,
  refreshWorkspaceRevisions,
  refreshWorkspaceMembers,
  handleEditorImageUpload,
  scheduleAutoSave,
  handleEditorBlockCommentBadgeClick,
  applyWorkspaceBlockCommentSummaries,
  workspaceFavoriteStorageKey,
  workspaceRecentStorageKey,
  workspaceSectionsStorageKey,
  workspacePageIndexViewsStorageKey,
  workspaceAssets,
  activeWorkspaceAssetId,
  currentUserEmail,
  workspacePageIndexRows,
  workspacePageIndexSelectedIds,
  collapsedWorkspacePageTreeIds,
  selectedBlockAnchor,
  workspaceCommentFilter,
  workspaceBlockCommentSummaries,
  workspacePropertySources,
  suppressWorkspacePropertyWatch,
  workspacePreferencesRemoteReady,
  workspacePreferencesDirtyBeforeRemoteLoad,
  loadWorkspacePreferencesFromLocal,
  loadWorkspacePreferences,
  refreshWorkspaceDocuments,
  loadFavoriteWorkspaceDocuments,
  loadRecentWorkspaceDocuments,
  loadWorkspaceDocumentSections,
  loadWorkspacePageIndexViews,
  pruneWorkspaceTreeEditingState,
  connectWorkspaceAssetRealtime,
  refreshWorkspaceBacklinks,
  disconnectWorkspaceAssetRealtime,
  clearWorkspaceDocumentLinkCopyTimer,
  clearWorkspaceNoticeTimer,
  closeWorkspaceConfirm,
  clearWorkspacePreferencesSaveTimer,
  destroyEditor: providedDestroyEditor,
}) => {
  const { syncTheme } = useWorkspaceThemeSync()
  const { handleSseRoleChanged } = useWorkspaceSseRoleChange({
    workspaceId,
    router,
    showWorkspaceNotice,
    allowNextRouteLeave,
    allowNextWindowUnload,
  })

  useWorkspaceLifecycleBindings({
    routeLeaveHandler: handleRouteLeave,
    routeUpdateHandler: handleRouteUpdate,
    windowEvents: [
      { type: 'sse-role-changed', handler: handleSseRoleChanged },
      { type: 'beforeunload', handler: handleBeforeUnload },
      { type: 'keydown', handler: handleWorkspaceGlobalKeydown },
      { type: 'click', handler: closeRoleDropdown },
    ],
  })

  const {
    prepareWorkspaceData,
    checkAndRedirectUuid,
  } = useWorkspaceDocumentLoader({
    route,
    router,
    api,
  })

  const {
    setupEditor,
    destroyEditor,
  } = useWorkspaceEditorSetup({
    editorHolder,
    editorApi,
    isEditorLoading,
    saveState,
    saveError,
    lastSavedAt,
    title,
    titleDirty,
    workspaceTemplateApplied,
    workspaceTemplateApplying,
    workspaceId,
    workspaceAccessRole,
    workspaceShareStatus,
    workspaceUuid,
    showWorkspaceShareModal,
    router,
    authStore,
    shouldWorkspaceEditorReadOnly,
    currentWorkspaceProperties,
    workspaceParentPageId,
    workspaceParentPageTitle,
    workspaceDocumentById,
    clearAutoSaveTimer,
    resetLeaveGuardBypass,
    prepareWorkspaceData,
    normalizeWorkspaceShareStatus: (status, type) => normalizeWorkspaceShareStatus(status, type),
    trackRecentWorkspaceDocument: (document) => trackRecentWorkspaceDocument(document),
    applyWorkspaceProperties: (properties) => applyWorkspaceProperties(properties),
    applyWorkspaceParentPage: (parent) => applyWorkspaceParentPage(parent),
    extractWorkspacePropertiesFromContents: (contents) => extractWorkspacePropertiesFromContents(contents),
    extractWorkspaceParentFromContents: (contents) => extractWorkspaceParentFromContents(contents),
    refreshWorkspaceAssets: (targetWorkspaceId) => refreshWorkspaceAssets(targetWorkspaceId),
    refreshWorkspaceComments: (targetWorkspaceId) => refreshWorkspaceComments(targetWorkspaceId),
    refreshWorkspaceRevisions: (targetWorkspaceId) => refreshWorkspaceRevisions(targetWorkspaceId),
    refreshWorkspaceMembers: (targetWorkspaceId) => refreshWorkspaceMembers(targetWorkspaceId),
    handleEditorImageUpload,
    scheduleAutoSave,
    handleEditorBlockCommentBadgeClick: (block) => handleEditorBlockCommentBadgeClick(block),
    applyWorkspaceBlockCommentSummaries: () => applyWorkspaceBlockCommentSummaries(),
  })

  useWorkspaceLifecycleWatchers({
    route,
    workspaceFavoriteStorageKey,
    workspaceRecentStorageKey,
    workspaceSectionsStorageKey,
    workspacePageIndexViewsStorageKey,
    workspaceAssets,
    activeWorkspaceAssetId,
    currentUserEmail,
    workspacePageIndexRows,
    workspacePageIndexSelectedIds,
    collapsedWorkspacePageTreeIds,
    workspaceId,
    selectedBlockAnchor,
    workspaceCommentFilter,
    workspaceBlockCommentSummaries,
    workspacePropertySources,
    suppressWorkspacePropertyWatch,
    isEditorLoading,
    editorApi,
    shouldWorkspaceEditorReadOnly,
    workspacePreferencesRemoteReady,
    workspacePreferencesDirtyBeforeRemoteLoad,
    syncTheme,
    loadWorkspacePreferencesFromLocal,
    loadWorkspacePreferences,
    refreshWorkspaceDocuments,
    checkAndRedirectUuid,
    setupEditor,
    loadFavoriteWorkspaceDocuments,
    loadRecentWorkspaceDocuments,
    loadWorkspaceDocumentSections,
    loadWorkspacePageIndexViews,
    pruneWorkspaceTreeEditingState,
    connectWorkspaceAssetRealtime,
    refreshWorkspaceBacklinks,
    applyWorkspaceBlockCommentSummaries,
    scheduleAutoSave,
    disconnectWorkspaceAssetRealtime,
    clearAutoSaveTimer,
    clearWorkspaceDocumentLinkCopyTimer,
    clearWorkspaceNoticeTimer,
    closeWorkspaceConfirm,
    clearWorkspacePreferencesSaveTimer,
    destroyEditor: providedDestroyEditor || destroyEditor,
  })
}
