apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-configmap.yaml
  - mariadb-statefulset.yaml
  - mariadb-bootstrap-job.yaml
  - infra-service.yaml
  - redis-hpa.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - websocket-server-service.yaml
  - websocket-server-deployment.yaml
  - frontend-configmap.yaml
  - service.yaml
  - frontend-deployment.yaml
