apiVersion: v1
kind: Service
metadata:
  name: {{ include "wafflebear.fullname" . }}-websocket-preview
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: websocket
    app.kubernetes.io/part-of: wafflebear
  ports:
    - name: ws
      protocol: TCP
      port: {{ .Values.websocket.service.port }}
      targetPort: {{ .Values.websocket.service.port }}
