<script setup>
import { ref, watch } from 'vue'

import WorkspaceDatabaseBoardPanels from './WorkspaceDatabaseBoardPanels.vue'
import WorkspaceFloatingSidebar from './WorkspaceFloatingSidebar.vue'
import WorkspaceLinkedHistoryPanels from './WorkspaceLinkedHistoryPanels.vue'
import WorkspaceOverviewPanels from './WorkspaceOverviewPanels.vue'
import WorkspacePageTreeBridge from './WorkspacePageTreeBridge.vue'
import WorkspaceReviewAssetsPanels from './WorkspaceReviewAssetsPanels.vue'
import WorkspaceScheduleInboxPanels from './WorkspaceScheduleInboxPanels.vue'
import WorkspaceUtilityPanels from './WorkspaceUtilityPanels.vue'

const props = defineProps({
  model: {
    type: Object,
    required: true,
  },
  actions: {
    type: Object,
    required: true,
  },
})

const linkedHistoryPanels = ref(null)
const reviewAssetsPanels = ref(null)

watch(linkedHistoryPanels, (value) => props.actions.registerSubpageInput?.(value), { immediate: true })
watch(reviewAssetsPanels, (value) => props.actions.registerCommentInput?.(value), { immediate: true })
</script>

<template>
  <WorkspaceFloatingSidebar
    :active-tab="model.activeWorkspacePanelTab"
    :collapsed="model.isWorkspacePanelCollapsed"
    :tabs="model.workspacePanelTabs"
    @update:active-tab="actions.setValue('activeWorkspacePanelTab', $event)"
  >
    <WorkspaceOverviewPanels
      :active-tab="model.activeWorkspacePanelTab"
      :is-panel-visible="model.isWorkspacePanelVisible"
      :loading="model.workspacePageIndexLoading"
      :home-metric-cards="model.workspaceHomeMetricCards"
      :home-attention-items="model.workspaceHomeAttentionItems"
      :home-queue-items="model.workspaceHomeMyQueue"
      :home-recent-pages="model.workspaceHomeRecentPages"
      :block-count="model.documentBlockCount"
      :summary-cards="model.workspaceSummaryCards"
      :health-items="model.workspaceHealthItems"
      :active-users="model.activeUsers"
      :access-role="model.workspaceAccessRole"
      :share-status-label="model.workspaceShareStatusLabel"
      :permission-items="model.workspacePermissionItems"
      :can-manage-share="model.canManageWorkspaceShare"
      :can-manage-assets="model.canManageAssets"
      :can-comment="model.canCommentOnWorkspace"
      :is-valid="model.isValid"
      :is-saving="model.isSaving"
      :is-editor-loading="model.isEditorLoading"
      :share-button-title="model.workspaceShareButtonTitle"
      :asset-uploading="model.workspaceAssetUploading"
      :workspace-id="model.workspaceId"
      :member-summary-label="model.workspaceMemberSummaryLabel"
      :member-error="model.workspaceMemberError"
      :member-loading="model.workspaceMemberLoading"
      :member-rows="model.workspaceMemberRows"
      :role-label="model.roleLabel"
      :user-initial="model.userInitial"
      :is-member-busy="model.isWorkspaceMemberBusy"
      :workload-rows="model.workspaceWorkloadRows"
      :search-query="model.workspaceFullTextQuery"
      :search-results="model.workspaceFullTextResults"
      :search-loading="model.workspaceFullTextLoading"
      :search-error="model.workspaceFullTextError"
      :can-search="model.canSearchWorkspaceFullText"
      :can-modify-page="model.canModifyWorkspacePage"
      :has-editor="model.hasEditor"
      @refresh="actions.refreshWorkspacePageIndex()"
      @open-home-metric="actions.openWorkspaceHomeMetric"
      @open-home-attention="actions.openWorkspaceHomeAttentionItem"
      @open-home-queue="actions.openWorkspaceHomeQueueItem"
      @open-document="actions.openWorkspaceDocument"
      @open-panel="actions.setValue('activeWorkspacePanelTab', $event)"
      @open-share="actions.openWorkspaceShare"
      @trigger-file-select="actions.triggerFileSelect"
      @focus-comment="actions.focusWorkspaceCommentComposer"
      @refresh-members="actions.refreshWorkspaceMembers()"
      @change-member-role="actions.handleWorkspaceMemberRoleSelect"
      @remove-member="actions.removeWorkspaceMember"
      @focus-task="actions.focusWorkspaceInboxTask"
      @update:search-query="actions.setValue('workspaceFullTextQuery', $event)"
      @search="actions.searchWorkspaceContents"
      @copy-link="actions.copyWorkspaceDocumentLink"
      @insert-link="actions.insertWorkspacePageLink"
    />

    <WorkspacePageTreeBridge
      :active-tab="model.activeWorkspacePanelTab"
      :is-panel-visible="model.isWorkspacePanelVisible"
      :query="model.workspacePageTreeQuery"
      :subpage-title="model.workspaceTreeSubpageTitle"
      :rename-draft="model.workspaceTreeRenameDraft"
      :move-target-id="model.workspaceTreeMoveTargetId"
      :loading="model.workspacePageIndexLoading"
      :rows="model.workspacePageTreeVisibleRows"
      :empty-label="model.workspacePageTreeEmptyLabel"
      :collapsed-id-set="model.workspacePageTreeCollapsedIdSet"
      :subpage-error="model.workspaceTreeSubpageError"
      :rename-error="model.workspaceTreeRenameError"
      :move-error="model.workspaceTreeMoveError"
      :subpage-creating-id="model.workspaceTreeSubpageCreatingId"
      :subpage-composer-parent-id="model.workspaceTreeSubpageComposerParentId"
      :renaming-id="model.workspaceTreeRenamingId"
      :rename-saving-id="model.workspaceTreeRenameSavingId"
      :moving-id="model.workspaceTreeMovingId"
      :move-saving-id="model.workspaceTreeMoveSavingId"
      :can-modify-page="model.canModifyWorkspacePage"
      :has-editor="model.hasEditor"
      :is-document-link-copied="model.isWorkspaceDocumentLinkCopied"
      :move-target-options="model.workspaceTreeMoveTargetOptions"
      :can-apply-move="model.canApplyWorkspaceTreeMove"
      @update:query="actions.setValue('workspacePageTreeQuery', $event)"
      @update:subpage-title="actions.setValue('workspaceTreeSubpageTitle', $event)"
      @update:rename-draft="actions.setValue('workspaceTreeRenameDraft', $event)"
      @update:move-target-id="actions.setValue('workspaceTreeMoveTargetId', $event)"
      @refresh="actions.refreshWorkspacePageIndex()"
      @toggle-node="actions.toggleWorkspacePageTreeNode"
      @open-document="actions.openWorkspaceDocument"
      @open-rename="actions.openWorkspaceTreeRename"
      @open-subpage="actions.openWorkspaceTreeSubpageComposer"
      @open-move="actions.openWorkspaceTreeMove"
      @copy-link="actions.copyWorkspaceDocumentLink"
      @insert-link="actions.insertWorkspacePageLink"
      @rename-page="actions.renameWorkspaceTreePage"
      @cancel-rename="actions.cancelWorkspaceTreeRename"
      @move-page="actions.moveWorkspaceTreePage"
      @cancel-move="actions.cancelWorkspaceTreeMove"
      @create-subpage="actions.createWorkspaceTreeSubpage"
      @cancel-subpage="actions.cancelWorkspaceTreeSubpageComposer"
    />

    <div v-if="model.activeWorkspacePanelTab === 'all'" class="workspace-floating-divider"></div>

    <WorkspaceDatabaseBoardPanels
      :active-tab="model.activeWorkspacePanelTab"
      :is-panel-visible="model.isWorkspacePanelVisible"
      :loading="model.workspacePageIndexLoading"
      :error="model.workspacePageIndexError"
      :database-filter="model.workspacePageIndexFilter"
      :database-filter-options="model.workspacePageIndexFilterOptions"
      :database-query="model.workspacePageIndexQuery"
      :database-sort="model.workspacePageIndexSort"
      :database-sort-options="model.workspacePageIndexSortOptions"
      :database-owner-filter="model.workspacePageIndexOwnerFilter"
      :database-owner-filter-options="model.workspacePageIndexOwnerFilterOptions"
      :database-tag-filter="model.workspacePageIndexTagFilter"
      :database-tag-options="model.workspacePageIndexTagOptions"
      :database-views="model.workspacePageIndexViews"
      :database-active-view="model.activeWorkspacePageIndexView"
      :database-view-name="model.workspacePageIndexViewName"
      :database-can-create-view="model.canCreateWorkspacePageIndexView"
      :database-visible-editable-rows="model.visibleEditableWorkspacePageIndexRows"
      :database-selected-rows="model.selectedWorkspacePageIndexRows"
      :database-all-visible-rows-selected="model.areAllVisibleWorkspacePageIndexRowsSelected"
      :database-can-apply-bulk-update="model.canApplyWorkspacePageIndexBulkUpdate"
      :database-bulk-status="model.workspacePageIndexBulkStatus"
      :database-bulk-priority="model.workspacePageIndexBulkPriority"
      :database-bulk-owner-email="model.workspacePageIndexBulkOwnerEmail"
      :database-bulk-due-date="model.workspacePageIndexBulkDueDate"
      :database-bulk-clear-due-date="model.workspacePageIndexBulkClearDueDate"
      :database-bulk-updating="model.workspacePageIndexBulkUpdating"
      :owner-candidates="model.workspacePropertyOwnerCandidates"
      :status-options="model.workspacePropertyStatusOptions"
      :priority-options="model.workspacePropertyPriorityOptions"
      :database-rows="model.visibleWorkspacePageIndexRows"
      :database-owner-options="model.workspacePageIndexOwnerOptions"
      :is-database-row-selected="model.isWorkspacePageIndexRowSelected"
      :is-row-updating="model.isWorkspacePageIndexRowUpdating"
      :database-view-summary="model.workspacePageIndexViewSummary"
      :board-rows="model.workspaceBoardRows"
      :board-columns="model.workspaceBoardColumns"
      :board-dragging-id="model.workspaceBoardDraggingId"
      :board-drag-over-status="model.workspaceBoardDragOverStatus"
      @refresh="actions.refreshWorkspacePageIndex()"
      @update:database-filter="actions.setValue('workspacePageIndexFilter', $event)"
      @update:database-query="actions.setValue('workspacePageIndexQuery', $event)"
      @update:database-sort="actions.setValue('workspacePageIndexSort', $event)"
      @update:database-owner-filter="actions.setValue('workspacePageIndexOwnerFilter', $event)"
      @update:database-tag-filter="actions.setValue('workspacePageIndexTagFilter', $event)"
      @update:database-view-name="actions.setValue('workspacePageIndexViewName', $event)"
      @update:database-bulk-status="actions.setValue('workspacePageIndexBulkStatus', $event)"
      @update:database-bulk-priority="actions.setValue('workspacePageIndexBulkPriority', $event)"
      @update:database-bulk-owner-email="actions.setValue('workspacePageIndexBulkOwnerEmail', $event)"
      @update:database-bulk-due-date="actions.setValue('workspacePageIndexBulkDueDate', $event)"
      @update:database-bulk-clear-due-date="actions.setValue('workspacePageIndexBulkClearDueDate', $event)"
      @apply-view="actions.applyWorkspacePageIndexView"
      @remove-view="actions.removeWorkspacePageIndexView"
      @create-view="actions.createWorkspacePageIndexView"
      @toggle-visible-selection="actions.toggleVisibleWorkspacePageIndexSelection"
      @toggle-row-selection="actions.toggleWorkspacePageIndexRowSelection"
      @apply-bulk="actions.updateWorkspacePageIndexBulkProperties"
      @clear-selection="actions.clearWorkspacePageIndexSelection"
      @open-row="actions.openWorkspaceDocument"
      @update-row-status="actions.updateWorkspacePageIndexRowStatus"
      @update-row-priority="actions.updateWorkspacePageIndexRowPriority"
      @update-row-owner="actions.updateWorkspacePageIndexRowOwner"
      @update-row-due-date="actions.updateWorkspacePageIndexRowDueDate"
      @update-row-tags="actions.updateWorkspacePageIndexRowTags"
      @set-board-drop-target="actions.setWorkspaceBoardDropTarget"
      @clear-board-drop-target="actions.clearWorkspaceBoardDropTarget"
      @drop-board-status="actions.dropWorkspaceBoardCardStatus"
      @start-board-drag="actions.startWorkspaceBoardCardDrag"
      @clear-board-drag="actions.clearWorkspaceBoardDrag"
      @move-board-status="actions.moveWorkspaceBoardCardStatus"
    />

    <div v-if="model.activeWorkspacePanelTab === 'all'" class="workspace-floating-divider"></div>

    <WorkspaceScheduleInboxPanels
      :active-tab="model.activeWorkspacePanelTab"
      :is-panel-visible="model.isWorkspacePanelVisible"
      :loading="model.workspacePageIndexLoading"
      :timeline-filter="model.workspaceTimelineFilter"
      :timeline-filter-options="model.workspaceTimelineFilterOptions"
      :timeline-range="model.workspaceTimelineRange"
      :timeline-groups="model.workspaceTimelineGroups"
      :timeline-empty-label="model.workspaceTimelineEmptyLabel"
      :timeline-item-style="model.workspaceTimelineItemStyle"
      :calendar-filter="model.workspaceCalendarFilter"
      :calendar-filter-options="model.workspaceCalendarFilterOptions"
      :calendar-groups="model.workspaceCalendarGroups"
      :calendar-empty-label="model.workspaceCalendarEmptyLabel"
      :today-key="model.todayKey"
      :inbox-open-task-count="model.inboxOpenTaskCount"
      :inbox-filter-options="model.workspaceInboxFilterOptions"
      :inbox-filter="model.workspaceInboxFilter"
      :inbox-tasks="model.visibleWorkspaceInboxTasks"
      :inbox-empty-label="model.workspaceInboxEmptyLabel"
      :is-task-toggling="model.isWorkspaceInboxTaskToggling"
      @refresh="actions.refreshWorkspacePageIndex()"
      @update:timeline-filter="actions.setValue('workspaceTimelineFilter', $event)"
      @update:calendar-filter="actions.setValue('workspaceCalendarFilter', $event)"
      @update:inbox-filter="actions.setValue('workspaceInboxFilter', $event)"
      @toggle-calendar-task="actions.toggleWorkspaceCalendarTask"
      @open-calendar-item="actions.openWorkspaceCalendarItem"
      @toggle-inbox-task="actions.toggleWorkspaceInboxTask"
      @focus-inbox-task="actions.focusWorkspaceInboxTask"
    />

    <div v-if="model.activeWorkspacePanelTab === 'all'" class="workspace-floating-divider"></div>

    <WorkspaceUtilityPanels
      :active-tab="model.activeWorkspacePanelTab"
      :is-panel-visible="model.isWorkspacePanelVisible"
      :activity-items="model.workspaceActivityItems"
      :quick-block-options="model.workspaceQuickBlockOptions"
      :quick-block-text="model.workspaceQuickBlockText"
      :quick-block-adding="model.workspaceQuickBlockAdding"
      :can-insert-quick-block="model.canInsertWorkspaceQuickBlock"
      :can-modify-page="model.canModifyWorkspacePage"
      :is-page-locked="model.isWorkspacePageLocked"
      :open-document-tasks="model.openDocumentTasks"
      :document-tasks="model.documentTasks"
      :visible-document-tasks="model.visibleDocumentTasks"
      :task-filter-options="model.workspaceTaskFilterOptions"
      :task-assignee-candidates="model.workspaceTaskAssigneeCandidates"
      :new-task="model.newWorkspaceTask"
      :new-task-assignee="model.newWorkspaceTaskAssignee"
      :new-task-due-date="model.newWorkspaceTaskDueDate"
      :task-filter="model.workspaceTaskFilter"
      :task-empty-label="model.workspaceTaskEmptyLabel"
      :task-progress="model.documentTaskProgress"
      :task-summary-label="model.documentTaskSummaryLabel"
      :can-add-task="model.canAddWorkspaceTask"
      :task-adding="model.workspaceTaskAdding"
      :is-task-toggling="model.isWorkspaceTaskToggling"
      :outline="model.documentOutline"
      @insert-block="actions.insertWorkspaceQuickBlock"
      @update:quick-block-text="actions.setValue('workspaceQuickBlockText', $event)"
      @add-task="actions.addWorkspaceTask"
      @focus-task="actions.focusWorkspaceTaskItem"
      @toggle-task="actions.toggleWorkspaceTaskItem"
      @update:new-task="actions.setValue('newWorkspaceTask', $event)"
      @update:new-task-assignee="actions.setValue('newWorkspaceTaskAssignee', $event)"
      @update:new-task-due-date="actions.setValue('newWorkspaceTaskDueDate', $event)"
      @update:task-filter="actions.setValue('workspaceTaskFilter', $event)"
      @focus-outline-item="actions.focusWorkspaceOutlineItem"
    />

    <div v-if="model.activeWorkspacePanelTab === 'all'" class="workspace-floating-divider"></div>

    <WorkspaceLinkedHistoryPanels
      ref="linkedHistoryPanels"
      :active-tab="model.activeWorkspacePanelTab"
      :is-panel-visible="model.isWorkspacePanelVisible"
      :workspace-id="model.workspaceId"
      :relation-count="model.workspaceRelationCount"
      :parent-page="model.currentWorkspaceParentPage"
      :child-pages="model.currentWorkspaceChildPages"
      :linked-documents="model.linkedWorkspaceDocuments"
      :linked-empty-label="model.linkedWorkspaceDocumentEmptyLabel"
      :backlinks="model.workspaceBacklinks"
      :backlink-loading="model.workspaceBacklinkLoading"
      :backlink-error="model.workspaceBacklinkError"
      :backlink-empty-label="model.workspaceBacklinkEmptyLabel"
      :can-modify-page="model.canModifyWorkspacePage"
      :has-editor="model.hasEditor"
      :subpage-title="model.workspaceSubpageTitle"
      :subpage-creating="model.workspaceSubpageCreating"
      :subpage-error="model.workspaceSubpageError"
      :can-start-subpage="model.canStartWorkspaceSubpage"
      :can-create-subpage="model.canCreateWorkspaceSubpage"
      :revisions="model.workspaceRevisions"
      :revision-loading="model.workspaceRevisionLoading"
      :revision-error="model.workspaceRevisionError"
      :active-revision="model.activeWorkspaceRevision"
      :revision-diff="model.workspaceRevisionDiff"
      :diff-summary="model.workspaceRevisionDiffSummary"
      :diff-items="model.workspaceRevisionDiffItems"
      :preview-loading="model.workspaceRevisionPreviewLoading"
      :restoring="model.workspaceRevisionRestoring"
      :can-restore="model.canRestoreWorkspaceRevision"
      :revision-reason-label="model.workspaceRevisionReasonLabel"
      @refresh-backlinks="actions.refreshWorkspaceBacklinks()"
      @open-parent="actions.openWorkspaceParentPage"
      @open-document="actions.openWorkspaceDocument"
      @insert-link="actions.insertWorkspacePageLink"
      @copy-link="actions.copyWorkspaceDocumentLink"
      @focus-linked-source="actions.focusWorkspaceLinkedDocumentSource"
      @create-subpage="actions.createWorkspaceSubpage"
      @update:subpage-title="actions.setValue('workspaceSubpageTitle', $event)"
      @refresh-revisions="actions.refreshWorkspaceRevisions()"
      @preview-revision="actions.previewWorkspaceRevision"
      @restore-revision="actions.restoreWorkspaceRevision"
    />

    <div v-if="model.activeWorkspacePanelTab === 'all'" class="workspace-floating-divider"></div>

    <WorkspaceReviewAssetsPanels
      ref="reviewAssetsPanels"
      :active-tab="model.activeWorkspacePanelTab"
      :is-panel-visible="model.isWorkspacePanelVisible"
      :unresolved-comments="model.unresolvedWorkspaceComments"
      :comment-filters="model.workspaceCommentFilters"
      :comment-filter="model.workspaceCommentFilter"
      :can-comment="model.canCommentOnWorkspace"
      :selected-block-anchor="model.selectedBlockAnchor"
      :comment-anchor-label="model.commentAnchorLabel"
      :show-mention-menu="model.showWorkspaceMentionMenu"
      :can-use-mentions="model.canUseWorkspaceMentions"
      :mention-candidates="model.workspaceMentionCandidates"
      :new-comment="model.newWorkspaceComment"
      :comment-saving="model.workspaceCommentSaving"
      :comment-error="model.workspaceCommentError"
      :comment-loading="model.workspaceCommentLoading"
      :comments="model.workspaceComments"
      :visible-comments="model.visibleWorkspaceComments"
      :empty-label="model.workspaceCommentEmptyLabel"
      :edit-draft="model.workspaceCommentEditDraft"
      :is-mentioning-current-user="model.isWorkspaceCommentMentioningCurrentUser"
      :can-edit-comment="model.canEditWorkspaceComment"
      :is-comment-updating="model.isCommentUpdating"
      :is-comment-deleting="model.isCommentDeleting"
      :is-comment-editing="model.isWorkspaceCommentEditing"
      :is-comment-resolving="model.isCommentResolving"
      :assets="model.workspaceAssets"
      :asset-loading="model.workspaceAssetLoading"
      :has-assets="model.hasWorkspaceAssets"
      :active-asset-id="model.activeWorkspaceAssetId"
      :can-manage-assets="model.canManageAssets"
      :get-asset-badge="model.getWorkspaceAssetBadge"
      :is-deleting-asset="model.isDeletingAsset"
      :is-saving-asset="model.isSavingWorkspaceAsset"
      @clear-anchor="actions.clearWorkspaceCommentAnchor"
      @insert-mention="actions.insertWorkspaceMention"
      @create-comment="actions.createWorkspaceComment"
      @start-edit="actions.startWorkspaceCommentEdit"
      @delete-comment="actions.deleteWorkspaceComment"
      @focus-anchor="actions.focusWorkspaceCommentAnchor"
      @update-comment="actions.updateWorkspaceComment"
      @cancel-edit="actions.cancelWorkspaceCommentEdit"
      @toggle-resolved="actions.toggleWorkspaceCommentResolved"
      @update:comment-filter="actions.setValue('workspaceCommentFilter', $event)"
      @update:show-mention-menu="actions.setValue('showWorkspaceMentionMenu', $event)"
      @update:new-comment="actions.setValue('newWorkspaceComment', $event)"
      @update:edit-draft="actions.setValue('workspaceCommentEditDraft', $event)"
      @toggle-asset="actions.toggleWorkspaceAssetActions"
      @delete-asset="actions.handleAssetDelete"
      @save-asset-to-drive="actions.saveWorkspaceAssetToDrive"
      @download-asset="actions.downloadWorkspaceAsset"
    />
  </WorkspaceFloatingSidebar>
</template>
