<script setup>
import WorkspaceMainLayout from './WorkspaceMainLayout.vue'

defineProps({
  model: {
    type: Object,
    required: true,
  },
  actions: {
    type: Object,
    required: true,
  },
})
</script>

<template>
  <WorkspaceMainLayout
    :document-query="model.documentQuery"
    :section-name-draft="model.sectionNameDraft"
    :section-edit-draft="model.sectionEditDraft"
    :section-editing-id="model.sectionEditingId"
    :documents-loading="model.documentsLoading"
    :current-workspace-key="model.currentWorkspaceKey"
    :favorite-documents="model.favoriteDocuments"
    :recent-documents="model.recentDocuments"
    :document-sections="model.documentSections"
    :visible-section-views="model.visibleSectionViews"
    :sectioned-document-count="model.sectionedDocumentCount"
    :personal-documents="model.personalDocuments"
    :shared-documents="model.sharedDocuments"
    :can-modify-page="model.canModifyPage"
    :has-editor="model.hasEditor"
    :is-document-favorite="model.isDocumentFavorite"
    :document-section-id="model.documentSectionId"
    :is-document-action-loading="model.isDocumentActionLoading"
    :icon="model.icon"
    :cover-color="model.coverColor"
    :status="model.status"
    :priority="model.priority"
    :owner-email="model.ownerEmail"
    :due-date="model.dueDate"
    :tags-input="model.tagsInput"
    :presence-open="model.presenceOpen"
    :open-role-dropdown-id="model.openRoleDropdownId"
    :panel-collapsed="model.panelCollapsed"
    :inline-quick-block-text="model.inlineQuickBlockText"
    :title="model.title"
    :breadcrumbs="model.breadcrumbs"
    :cover-color-option="model.coverColorOption"
    :status-option="model.statusOption"
    :priority-option="model.priorityOption"
    :owner-candidates="model.ownerCandidates"
    :tags="model.tags"
    :save-status-class="model.saveStatusClass"
    :save-status-label="model.saveStatusLabel"
    :realtime-status-class="model.realtimeStatusClass"
    :realtime-status-label="model.realtimeStatusLabel"
    :share-status-class="model.shareStatusClass"
    :share-status-label="model.shareStatusLabel"
    :access-role-label="model.accessRoleLabel"
    :is-page-locked="model.isPageLocked"
    :lock-status-label="model.lockStatusLabel"
    :workspace-id="model.workspaceId"
    :link-copied="model.linkCopied"
    :active-user-preview="model.activeUserPreview"
    :extra-active-user-count="model.extraActiveUserCount"
    :active-users="model.activeUsers"
    :presence-summary-label="model.presenceSummaryLabel"
    :can-manage-share="model.canManageShare"
    :can-edit-workspace="model.canEditWorkspace"
    :is-valid="model.isValid"
    :is-saving="model.isSaving"
    :is-editor-loading="model.isEditorLoading"
    :can-favorite-document="model.canFavoriteDocument"
    :is-favorite="model.isFavorite"
    :favorite-title="model.favoriteTitle"
    :lock-button-title="model.lockButtonTitle"
    :can-copy-link="model.canCopyLink"
    :is-link-copied="model.isLinkCopied"
    :can-export-markdown="model.canExportMarkdown"
    :markdown-exporting="model.markdownExporting"
    :share-button-title="model.shareButtonTitle"
    :assets="model.assets"
    :images="model.images"
    :files="model.files"
    :asset-loading="model.assetLoading"
    :asset-uploading="model.assetUploading"
    :asset-error="model.assetError"
    :can-manage-assets="model.canManageAssets"
    :is-deleting-asset="model.isDeletingAsset"
    :can-show-templates="model.canShowTemplates"
    :templates="model.templates"
    :template-applying="model.templateApplying"
    :inline-quick-block-options="model.inlineQuickBlockOptions"
    :can-insert-quick-block="model.canInsertQuickBlock"
    :quick-block-adding="model.quickBlockAdding"
    :remote-cursors="model.remoteCursors"
    @update:document-query="actions.setValue('workspaceDocumentQuery', $event)"
    @update:section-name-draft="actions.setValue('workspaceSectionNameDraft', $event)"
    @update:section-edit-draft="actions.setValue('workspaceSectionEditDraft', $event)"
    @update:icon="actions.setValue('workspacePropertyIcon', $event)"
    @update:cover-color="actions.setValue('workspacePropertyCoverColor', $event)"
    @update:status="actions.setValue('workspacePropertyStatus', $event)"
    @update:priority="actions.setValue('workspacePropertyPriority', $event)"
    @update:owner-email="actions.setValue('workspacePropertyOwnerEmail', $event)"
    @update:due-date="actions.setValue('workspacePropertyDueDate', $event)"
    @update:tags-input="actions.setValue('workspacePropertyTagsInput', $event)"
    @update:presence-open="actions.setValue('showUserList', $event)"
    @update:open-role-dropdown-id="actions.setValue('openRoleDropdownId', $event)"
    @update:panel-collapsed="actions.setValue('isWorkspacePanelCollapsed', $event)"
    @update:inline-quick-block-text="actions.setValue('workspaceInlineQuickBlockText', $event)"
    @register-section-edit-input="actions.registerSectionEditInput"
    @open-command-palette="actions.openWorkspaceCommandPalette"
    @create-document="actions.createWorkspaceDocument"
    @create-section="actions.createWorkspaceDocumentSection"
    @save-section-rename="actions.saveWorkspaceDocumentSectionRename"
    @cancel-section-rename="actions.cancelWorkspaceDocumentSectionRename"
    @toggle-section="actions.toggleWorkspaceDocumentSection"
    @start-section-rename="actions.startWorkspaceDocumentSectionRename"
    @remove-section="actions.removeWorkspaceDocumentSection"
    @open-document="actions.openWorkspaceDocument"
    @toggle-document-favorite="actions.toggleFavoriteWorkspaceDocument"
    @move-section="actions.moveWorkspaceDocumentToSection"
    @insert-link="actions.insertWorkspacePageLink"
    @copy-link="actions.copyWorkspaceDocumentLink"
    @duplicate-document="actions.duplicateWorkspaceDocument"
    @remove-document="actions.removeWorkspaceDocument"
    @normalize-icon="actions.normalizeWorkspacePageIcon"
    @title-input="actions.handleTitleInput"
    @open-breadcrumb="actions.openWorkspaceDocument"
    @change-role="actions.handleRoleAction"
    @save="actions.handleSave"
    @toggle-current-favorite="actions.toggleCurrentWorkspaceDocumentFavorite"
    @toggle-lock="actions.toggleWorkspacePageLock"
    @copy-current-link="actions.copyCurrentWorkspaceDocumentLink"
    @export-markdown="actions.exportWorkspaceMarkdown"
    @open-share="actions.openWorkspaceShare"
    @asset-selection="actions.handleAssetSelection"
    @trigger-image-select="actions.triggerImageSelect"
    @trigger-file-select="actions.triggerFileSelect"
    @delete-asset="actions.handleAssetDelete"
    @download-asset="actions.downloadWorkspaceAsset"
    @apply-template="actions.applyWorkspaceTemplate"
    @insert-inline-block="actions.insertWorkspaceInlineQuickBlock"
    @register-image-input="actions.registerImageInput"
    @register-file-input="actions.registerFileInput"
    @register-editor-holder="actions.registerEditorHolder"
  />
</template>
