{{- if .Values.redis.sentinel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.sentinel.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis-sentinel
    app.kubernetes.io/part-of: wafflebear
  ports:
    - name: sentinel
      protocol: TCP
      port: {{ .Values.redis.sentinel.port }}
      targetPort: {{ .Values.redis.sentinel.port }}
{{- end }}
