apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.headlessService.name }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: wafflebear
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
